In [1]:
import math
from datetime import datetime,timedelta
import numpy as np
import pandas
import random
import preprocess_functions

In [2]:
df1 = pandas.read_csv("training_20min_avg_volume_etc_cartype.csv")
df2 = pandas.read_csv("training2_20min_avg_volume_etc_cartype.csv")
df = df1.append(df2, ignore_index=True)
df_time_temp = df['time_window'].str.split('[',expand=True)[1].str.split(',',expand=True)[0]
df['time_start'] = df_time_temp

In [3]:
df_1_0 = preprocess_functions.extract_tg_dir(df, 1, 0)
df_1_1 = preprocess_functions.extract_tg_dir(df, 1, 1)
df_2_0 = preprocess_functions.extract_tg_dir(df, 2, 0)
df_3_0 = preprocess_functions.extract_tg_dir(df, 3, 0)
df_3_1 = preprocess_functions.extract_tg_dir(df, 3, 1)
df_1_0

,tollgate_id,time_window,direction,volume,model0,model1,model2,model3,model4,model5,model6,model7,type0,type1,has_etc1,time_start
0,1,"[2016-09-19 00:00:00,2016-09-19 00:20:00)",0,13,0,10,1,0,0,2,0,0,0,0,4,2016-09-19 00:00:00
1,1,"[2016-09-19 00:20:00,2016-09-19 00:40:00)",0,6,0,6,0,0,0,0,0,0,0,0,1,2016-09-19 00:20:00
2,1,"[2016-09-19 00:40:00,2016-09-19 01:00:00)",0,9,0,6,1,0,1,1,0,0,0,0,1,2016-09-19 00:40:00
3,1,"[2016-09-19 01:00:00,2016-09-19 01:20:00)",0,10,0,7,0,0,0,3,0,0,0,0,1,2016-09-19 01:00:00
4,1,"[2016-09-19 01:20:00,2016-09-19 01:40:00)",0,14,1,10,1,1,0,1,0,0,0,0,3,2016-09-19 01:20:00
5,1,"[2016-09-19 01:40:00,2016-09-19 02:00:00)",0,10,0,9,0,0,0,1,0,0,0,0,0,2016-09-19 01:40:00
6,1,"[2016-09-19 02:00:00,2016-09-19 02:20:00)",0,7,0,3,1,0,1,2,0,0,0,0,1,2016-09-19 02:00:00
7,1,"[2016-09-19 02:20:00,2016-09-19 02:40:00)",0,10,0,3,5,0,0,2,0,0,0,0,1,2016-09-19 02:20:00
8,1,"[2016-09-19 02:40:00,2016-09-19 03:00:00)",0,6,0,0,1,3,1,1,0,0,0,0,0,2016-09-19 02:40:00
9,1,"[2016-09-19 03:00:00,2016-09-19 03:20:00)",0,9,0,5,2,0,0,2,0,0,0,0,0,2016-09-19 03:00:00
10,1,"[2016-09-19 03:20:00,2016-09-19 03:40:00)",0,4,0,3,0,1,0,0,0,0,0,0,1,2016-09-19 03:20:00
11,1,"[2016-09-19 03:40:00,2016-09-19 04:00:00)",0,9,0,5,1,2,0,1,0,0,0,0,2,2016-09-19 03:40:00
12,1,"[2016-09-19 04:00:00,2016-09-19 04:20:00)",0,10,0,6,2,1,0,1,0,0,0,0,0,2016-09-19 04:00:00
13,1,"[2016-09-19 04:20:00,2016-09-19 04:40:00)",0,13,0,9,2,1,0,1,0,0,0,0,0,2016-09-19 04:20:00
14,1,"[2016-09-19 04:40:00,2016-09-19 05:00:00)",0,12,0,8,2,1,0,1,0,0,0,0,0,2016-09-19 04:40:00
15,1,"[2016-09-19 05:00:00,2016-09-19 05:20:00)",0,2,0,0,2,0,0,0,0,0,0,0,0,2016-09-19 05:00:00
16,1,"[2016-09-19 05:20:00,2016-09-19 05:40:00)",0,8,0,6,2,0,0,0,0,0,0,0,2,2016-09-19 05:20:00
17,1,"[2016-09-19 05:40:00,2016-09-19 06:00:00)",0,13,0,12,1,0,0,0,0,0,0,0,2,2016-09-19 05:40:00
18,1,"[2016-09-19 06:00:00,2016-09-19 06:20:00)",0,8,0,7,0,1,0,0,0,0,0,0,2,2016-09-19 06:00:00
19,1,"[2016-09-19 06:20:00,2016-09-19 06:40:00)",0,13,0,12,1,0,0,0,0,0,0,0,5,2016-09-19 06:20:00
20,1,"[2016-09-19 06:40:00,2016-09-19 07:00:00)",0,32,0,28,2,1,1,0,0,0,0,0,9,2016-09-19 06:40:00
21,1,"[2016-09-19 07:00:00,2016-09-19 07:20:00)",0,39,0,34,3,1,1,0,0,0,0,0,10,2016-09-19 07:00:00
22,1,"[2016-09-19 07:20:00,2016-09-19 07:40:00)",0,31,0,30,1,0,0,0,0,0,0,0,11,2016-09-19 07:20:00
23,1,"[2016-09-19 07:40:00,2016-09-19 08:00:00)",0,43,0,40,2,1,0,0,0,0,0,0,16,2016-09-19 07:40:00
24,1,"[2016-09-19 08:00:00,2016-09-19 08:20:00)",0,46,0,42,3,1,0,0,0,0,0,0,17,2016-09-19 08:00:00
25,1,"[2016-09-19 08:20:00,2016-09-19 08:40:00)",0,56,0,49,4,2,1,0,0,0,0,0,17,2016-09-19 08:20:00
26,1,"[2016-09-19 08:40:00,2016-09-19 09:00:00)",0,41,9,30,1,1,0,0,0,0,0,0,9,2016-09-19 08:40:00
27,1,"[2016-09-19 09:00:00,2016-09-19 09:20:00)",0,50,0,44,6,0,0,0,0,0,0,0,18,2016-09-19 09:00:00
28,1,"[2016-09-19 09:20:00,2016-09-19 09:40:00)",0,49,0,41,7,0,1,0,0,0,0,0,10,2016-09-19 09:20:00
29,1,"[2016-09-19 09:40:00,2016-09-19 10:00:00)",0,44,0,42,2,0,0,0,0,0,0,0,3,2016-09-19 09:40:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2562,1,"[2016-10-24 14:00:00,2016-10-24 14:20:00)",0,47,0,40,5,2,0,0,0,0,0,0,15,2016-10-24 14:00:00
2563,1,"[2016-10-24 14:20:00,2016-10-24 14:40:00)",0,49,0,40,9,0,0,0,0,0,0,0,8,2016-10-24 14:20:00
2564,1,"[2016-10-24 14:40:00,2016-10-24 15:00:00)",0,44,0,40,4,0,0,0,0,0,0,0,9,2016-10-24 14:40:00
2565,1,"[2016-10-24 15:00:00,2016-10-24 15:20:00)",0,50,0,46,3,1,0,0,0,0,0,0,3,2016-10-24 15:00:00
2566,1,"[2016-10-24 15:20:00,2016-10-24 15:40:00)",0,47,0,43,4,0,0,0,0,0,0,0,13,2016-10-24 15:20:00
2567,1,"[2016-10-24 15:40:00,2016-10-24 16:00:00)",0,26,0,25,1,0,0,0,0,0,0,0,7,2016-10-24 15:40:00
2568,1,"[2016-10-24 16:00:00,2016-10-24 16:20:00)",0,49,0,47,2,0,0,0,0,0,0,0,7,2016-10-24 16:00:00
2569,1,"[2016-10-24 16:20:00,2016-10-24 16:40:00)",0,50,0,44,4,1,1,0,0,0,0,0,15,2016-10-24 16:20:00
2570,1,"[2016-10-24 16:40:00,2016-10-24 17:00:00)",0,44,0,40,3,0,1,0,0,0,0,0,11,2016-10-24 16:40:00
2571,1,"[2016-10-24 17:00:00,2016-10-24 17:20:00)",0,32,0,30,2,0,0,0,0,0,0,0,6,2016-10-24 17:00:00
2572,1,"[2016-10-24 17:20:00,2016-10-24 17:40:00)",0,39,0,36,0,0,3,0,0,0,0,0,13,2016-10-24 17:20:00
2573,1,"[2016-10-24 17:40:00,2016-10-24 18:00:00)",0,29,0,28,1,0,0,0,0,0,0,0,10,2016-10-24 17:40:00
2574,1,"[2016-10-24 18:00:00,2016-10-24 18:20:00)",0,15,0,12,3,0,0,0,0,0,0,0,3,2016-10-24 18:00:00
2575,1,"[2016-10-24 18:20:00,2016-10-24 18:40:00)",0,18,0,17,1,0,0,0,0,0,0,0,3,2016-10-24 18:20:00
2576,1,"[2016-10-24 18:40:00,2016-10-24 19:00:00)",0,13,0,13,0,0,0,0,0,0,0,0,5,2016-10-24 18:40:00
2577,1,"[2016-10-24 19:00:00,2016-10-24 19:20:00)",0,27,0,27,0,0,0,0,0,0,0,0,4,2016-10-24 19:00:00
2578,1,"[2016-10-24 19:20:00,2016-10-24 19:40:00)",0,16,0,15,1,0,0,0,0,0,0,0,4,2016-10-24 19:20:00
2579,1,"[2016-10-24 19:40:00,2016-10-24 20:00:00)",0,10,0,10,0,0,0,0,0,0,0,0,2,2016-10-24 19:40:00
2580,1,"[2016-10-24 20:00:00,2016-10-24 20:20:00)",0,18,0,17,1,0,0,0,0,0,0,0,7,2016-10-24 20:00:00
2581,1,"[2016-10-24 20:20:00,2016-10-24 20:40:00)",0,19,0,17,2,0,0,0,0,0,0,0,6,2016-10-24 20:20:00
2582,1,"[2016-10-24 20:40:00,2016-10-24 21:00:00)",0,17,0,13,3,0,1,0,0,0,0,0,5,2016-10-24 20:40:00
2583,1,"[2016-10-24 21:00:00,2016-10-24 21:20:00)",0,19,0,15,4,0,0,0,0,0,0,0,5,2016-10-24 21:00:00
2584,1,"[2016-10-24 21:20:00,2016-10-24 21:40:00)",0,14,0,12,2,0,0,0,0,0,0,0,3,2016-10-24 21:20:00
2585,1,"[2016-10-24 21:40:00,2016-10-24 22:00:00)",0,14,0,13,1,0,0,0,0,0,0,0,1,2016-10-24 21:40:00
2586,1,"[2016-10-24 22:00:00,2016-10-24 22:20:00)",0,10,0,10,0,0,0,0,0,0,0,0,2,2016-10-24 22:00:00
2587,1,"[2016-10-24 22:20:00,2016-10-24 22:40:00)",0,11,0,9,2,0,0,0,0,0,0,0,2,2016-10-24 22:20:00
2588,1,"[2016-10-24 22:40:00,2016-10-24 23:00:00)",0,7,0,5,2,0,0,0,0,0,0,0,3,2016-10-24 22:40:00
2589,1,"[2016-10-24 23:00:00,2016-10-24 23:20:00)",0,11,0,8,3,0,0,0,0,0,0,0,1,2016-10-24 23:00:00
2590,1,"[2016-10-24 23:20:00,2016-10-24 23:40:00)",0,7,0,7,0,0,0,0,0,0,0,0,1,2016-10-24 23:20:00
2591,1,"[2016-10-24 23:40:00,2016-10-25 00:00:00)",0,2,0,2,0,0,0,0,0,0,0,0,0,2016-10-24 23:40:00

In [4]:
df_filled = pandas.read_csv('phase2_filled_vacancy.csv')
df_1_0_update = preprocess_functions.update_vacancy_volume(df_1_0, df_filled)
df_1_1_update = preprocess_functions.update_vacancy_volume(df_1_1, df_filled)
df_2_0_update = preprocess_functions.update_vacancy_volume(df_2_0, df_filled)
df_3_0_update = preprocess_functions.update_vacancy_volume(df_3_0, df_filled)
df_3_1_update = preprocess_functions.update_vacancy_volume(df_3_1, df_filled)

In [5]:
df_1_0_new = preprocess_functions.add_last2h_dimension(df_1_0_update, 'volume')
df_1_1_new = preprocess_functions.add_last2h_dimension(df_1_1_update, 'volume')
df_2_0_new = preprocess_functions.add_last2h_dimension(df_2_0_update, 'volume')
df_3_0_new = preprocess_functions.add_last2h_dimension(df_3_0_update, 'volume')
df_3_1_new = preprocess_functions.add_last2h_dimension(df_3_1_update, 'volume')
for i in xrange(8):
    df_1_0_new = preprocess_functions.add_last2h_dimension(df_1_0_new, 'model'+'%d'%i)
    df_1_1_new = preprocess_functions.add_last2h_dimension(df_1_1_new, 'model'+'%d'%i)
    df_2_0_new = preprocess_functions.add_last2h_dimension(df_2_0_new, 'model'+'%d'%i)
    df_3_0_new = preprocess_functions.add_last2h_dimension(df_3_0_new, 'model'+'%d'%i)
    df_3_1_new = preprocess_functions.add_last2h_dimension(df_3_1_new, 'model'+'%d'%i)
for i in xrange(2):
    df_1_0_new = preprocess_functions.add_last2h_dimension(df_1_0_new, 'type'+'%d'%i)
    df_1_1_new = preprocess_functions.add_last2h_dimension(df_1_1_new, 'type'+'%d'%i)
    df_2_0_new = preprocess_functions.add_last2h_dimension(df_2_0_new, 'type'+'%d'%i)
    df_3_0_new = preprocess_functions.add_last2h_dimension(df_3_0_new, 'type'+'%d'%i)
    df_3_1_new = preprocess_functions.add_last2h_dimension(df_3_1_new, 'type'+'%d'%i)
df_1_0_new = preprocess_functions.add_last2h_dimension(df_1_0_new, 'has_etc1')
df_1_1_new = preprocess_functions.add_last2h_dimension(df_1_1_new, 'has_etc1')
df_2_0_new = preprocess_functions.add_last2h_dimension(df_2_0_new, 'has_etc1')
df_3_0_new = preprocess_functions.add_last2h_dimension(df_3_0_new, 'has_etc1')
df_3_1_new = preprocess_functions.add_last2h_dimension(df_3_1_new, 'has_etc1')
df_1_0_new

,tollgate_id,time_window,direction,volume,model0,model1,model2,model3,model4,model5,...,type1lv_mean,type1lv_var,has_etc1lv0,has_etc1lv1,has_etc1lv2,has_etc1lv3,has_etc1lv4,has_etc1lv5,has_etc1lv_mean,has_etc1lv_var
0,1,"[2016-09-19 00:00:00,2016-09-19 00:20:00)",0,13.0,0,10.0,1.0,0,0,2,...,0.0,0.0,4.0,1.0,1.0,1.0,3.0,0.0,1.666667,1.888889
1,1,"[2016-09-19 00:20:00,2016-09-19 00:40:00)",0,6.0,0,6.0,0.0,0,0,0,...,0.0,0.0,4.0,1.0,1.0,1.0,3.0,0.0,1.666667,1.888889
2,1,"[2016-09-19 00:40:00,2016-09-19 01:00:00)",0,9.0,0,6.0,1.0,0,1,1,...,0.0,0.0,4.0,1.0,1.0,1.0,3.0,0.0,1.666667,1.888889
3,1,"[2016-09-19 01:00:00,2016-09-19 01:20:00)",0,10.0,0,7.0,0.0,0,0,3,...,0.0,0.0,4.0,1.0,1.0,1.0,3.0,0.0,1.666667,1.888889
4,1,"[2016-09-19 01:20:00,2016-09-19 01:40:00)",0,14.0,1,10.0,1.0,1,0,1,...,0.0,0.0,4.0,1.0,1.0,1.0,3.0,0.0,1.666667,1.888889
5,1,"[2016-09-19 01:40:00,2016-09-19 02:00:00)",0,10.0,0,9.0,0.0,0,0,1,...,0.0,0.0,4.0,1.0,1.0,1.0,3.0,0.0,1.666667,1.888889
6,1,"[2016-09-19 02:00:00,2016-09-19 02:20:00)",0,7.0,0,3.0,1.0,0,1,2,...,0.0,0.0,4.0,1.0,1.0,1.0,3.0,0.0,1.666667,1.888889
7,1,"[2016-09-19 02:20:00,2016-09-19 02:40:00)",0,10.0,0,3.0,5.0,0,0,2,...,0.0,0.0,4.0,1.0,1.0,1.0,3.0,0.0,1.666667,1.888889
8,1,"[2016-09-19 02:40:00,2016-09-19 03:00:00)",0,6.0,0,0.0,1.0,3,1,1,...,0.0,0.0,4.0,1.0,1.0,1.0,3.0,0.0,1.666667,1.888889
9,1,"[2016-09-19 03:00:00,2016-09-19 03:20:00)",0,9.0,0,5.0,2.0,0,0,2,...,0.0,0.0,4.0,1.0,1.0,1.0,3.0,0.0,1.666667,1.888889
10,1,"[2016-09-19 03:20:00,2016-09-19 03:40:00)",0,4.0,0,3.0,0.0,1,0,0,...,0.0,0.0,4.0,1.0,1.0,1.0,3.0,0.0,1.666667,1.888889
11,1,"[2016-09-19 03:40:00,2016-09-19 04:00:00)",0,9.0,0,5.0,1.0,2,0,1,...,0.0,0.0,4.0,1.0,1.0,1.0,3.0,0.0,1.666667,1.888889
12,1,"[2016-09-19 04:00:00,2016-09-19 04:20:00)",0,10.0,0,6.0,2.0,1,0,1,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,2.0,0.833333,0.472222
13,1,"[2016-09-19 04:20:00,2016-09-19 04:40:00)",0,13.0,0,9.0,2.0,1,0,1,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,2.0,0.833333,0.472222
14,1,"[2016-09-19 04:40:00,2016-09-19 05:00:00)",0,12.0,0,8.0,2.0,1,0,1,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,2.0,0.833333,0.472222
15,1,"[2016-09-19 05:00:00,2016-09-19 05:20:00)",0,2.0,0,0.0,2.0,0,0,0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,2.0,0.833333,0.472222
16,1,"[2016-09-19 05:20:00,2016-09-19 05:40:00)",0,8.0,0,6.0,2.0,0,0,0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,2.0,0.833333,0.472222
17,1,"[2016-09-19 05:40:00,2016-09-19 06:00:00)",0,13.0,0,12.0,1.0,0,0,0,...,0.0,0.0,1.0,1.0,0.0,0.0,1.0,2.0,0.833333,0.472222
18,1,"[2016-09-19 06:00:00,2016-09-19 06:20:00)",0,8.0,0,7.0,0.0,1,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.666667,0.888889
19,1,"[2016-09-19 06:20:00,2016-09-19 06:40:00)",0,13.0,0,12.0,1.0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.666667,0.888889
20,1,"[2016-09-19 06:40:00,2016-09-19 07:00:00)",0,32.0,0,28.0,2.0,1,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.666667,0.888889
21,1,"[2016-09-19 07:00:00,2016-09-19 07:20:00)",0,39.0,0,34.0,3.0,1,1,0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.666667,0.888889
22,1,"[2016-09-19 07:20:00,2016-09-19 07:40:00)",0,31.0,0,30.0,1.0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.666667,0.888889
23,1,"[2016-09-19 07:40:00,2016-09-19 08:00:00)",0,43.0,0,40.0,2.0,1,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.666667,0.888889
24,1,"[2016-09-19 08:00:00,2016-09-19 08:20:00)",0,46.0,0,42.0,3.0,1,0,0,...,0.0,0.0,2.0,5.0,9.0,10.0,11.0,16.0,8.833333,19.805556
25,1,"[2016-09-19 08:20:00,2016-09-19 08:40:00)",0,56.0,0,49.0,4.0,2,1,0,...,0.0,0.0,2.0,5.0,9.0,10.0,11.0,16.0,8.833333,19.805556
26,1,"[2016-09-19 08:40:00,2016-09-19 09:00:00)",0,41.0,9,30.0,1.0,1,0,0,...,0.0,0.0,2.0,5.0,9.0,10.0,11.0,16.0,8.833333,19.805556
27,1,"[2016-09-19 09:00:00,2016-09-19 09:20:00)",0,50.0,0,44.0,6.0,0,0,0,...,0.0,0.0,2.0,5.0,9.0,10.0,11.0,16.0,8.833333,19.805556
28,1,"[2016-09-19 09:20:00,2016-09-19 09:40:00)",0,49.0,0,41.0,7.0,0,1,0,...,0.0,0.0,2.0,5.0,9.0,10.0,11.0,16.0,8.833333,19.805556
29,1,"[2016-09-19 09:40:00,2016-09-19 10:00:00)",0,44.0,0,42.0,2.0,0,0,0,...,0.0,0.0,2.0,5.0,9.0,10.0,11.0,16.0,8.833333,19.805556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2562,1,"[2016-10-24 14:00:00,2016-10-24 14:20:00)",0,47.0,0,40.0,5.0,2,0,0,...,0.0,0.0,10.0,14.0,9.0,13.0,13.0,12.0,11.833333,3.138889
2563,1,"[2016-10-24 14:20:00,2016-10-24 14:40:00)",0,49.0,0,40.0,9.0,0,0,0,...,0.0,0.0,10.0,14.0,9.0,13.0,13.0,12.0,11.833333,3.138889
2564,1,"[2016-10-24 14:40:00,2016-10-24 15:00:00)",0,44.0,0,40.0,4.0,0,0,0,...,0.0,0.0,10.0,14.0,9.0,13.0,13.0,12.0,11.833333,3.138889
2565,1,"[2016-10-24 15:00:00,2016-10-24 15:20:00)",0,50.0,0,46.0,3.0,1,0,0,...,0.0,0.0,10.0,14.0,9.0,13.0,13.0,12.0,11.833333,3.138889
2566,1,"[2016-10-24 15:20:00,2016-10-24 15:40:00)",0,47.0,0,43.0,4.0,0,0,0,...,0.0,0.0,10.0,14.0,9.0,13.0,13.0,12.0,11.833333,3.138889
2567,1,"[2016-10-24 15:40:00,2016-10-24 16:00:00)",0,26.0,0,25.0,1.0,0,0,0,...,0.0,0.0,10.0,14.0,9.0,13.0,13.0,12.0,11.833333,3.138889
2568,1,"[2016-10-24 16:00:00,2016-10-24 16:20:00)",0,49.0,0,47.0,2.0,0,0,0,...,0.0,0.0,15.0,8.0,9.0,3.0,13.0,7.0,9.166667,15.472222
2569,1,"[2016-10-24 16:20:00,2016-10-24 16:40:00)",0,50.0,0,44.0,4.0,1,1,0,...,0.0,0.0,15.0,8.0,9.0,3.0,13.0,7.0,9.166667,15.472222
2570,1,"[2016-10-24 16:40:00,2016-10-24 17:00:00)",0,44.0,0,40.0,3.0,0,1,0,...,0.0,0.0,15.0,8.0,9.0,3.0,13.0,7.0,9.166667,15.472222
2571,1,"[2016-10-24 17:00:00,2016-10-24 17:20:00)",0,32.0,0,30.0,2.0,0,0,0,...,0.0,0.0,3.0,13.0,7.0,7.0,15.0,11.0,9.333333,16.555556
2572,1,"[2016-10-24 17:20:00,2016-10-24 17:40:00)",0,39.0,0,36.0,0.0,0,3,0,...,0.0,0.0,3.0,13.0,7.0,7.0,15.0,11.0,9.333333,16.555556
2573,1,"[2016-10-24 17:40:00,2016-10-24 18:00:00)",0,29.0,0,28.0,1.0,0,0,0,...,0.0,0.0,3.0,13.0,7.0,7.0,15.0,11.0,9.333333,16.555556
2574,1,"[2016-10-24 18:00:00,2016-10-24 18:20:00)",0,15.0,0,12.0,3.0,0,0,0,...,0.0,0.0,3.0,13.0,7.0,7.0,15.0,11.0,9.333333,16.555556
2575,1,"[2016-10-24 18:20:00,2016-10-24 18:40:00)",0,18.0,0,17.0,1.0,0,0,0,...,0.0,0.0,3.0,13.0,7.0,7.0,15.0,11.0,9.333333,16.555556
2576,1,"[2016-10-24 18:40:00,2016-10-24 19:00:00)",0,13.0,0,13.0,0.0,0,0,0,...,0.0,0.0,3.0,13.0,7.0,7.0,15.0,11.0,9.333333,16.555556
2577,1,"[2016-10-24 19:00:00,2016-10-24 19:20:00)",0,27.0,0,27.0,0.0,0,0,0,...,0.0,0.0,7.0,15.0,11.0,6.0,13.0,10.0,10.333333,9.888889
2578,1,"[2016-10-24 19:20:00,2016-10-24 19:40:00)",0,16.0,0,15.0,1.0,0,0,0,...,0.0,0.0,7.0,15.0,11.0,6.0,13.0,10.0,10.333333,9.888889
2579,1,"[2016-10-24 19:40:00,2016-10-24 20:00:00)",0,10.0,0,10.0,0.0,0,0,0,...,0.0,0.0,7.0,15.0,11.0,6.0,13.0,10.0,10.333333,9.888889
2580,1,"[2016-10-24 20:00:00,2016-10-24 20:20:00)",0,18.0,0,17.0,1.0,0,0,0,...,0.0,0.0,3.0,3.0,5.0,4.0,4.0,2.0,3.500000,0.916667
2581,1,"[2016-10-24 20:20:00,2016-10-24 20:40:00)",0,19.0,0,17.0,2.0,0,0,0,...,0.0,0.0,3.0,3.0,5.0,4.0,4.0,2.0,3.500000,0.916667
2582,1,"[2016-10-24 20:40:00,2016-10-24 21:00:00)",0,17.0,0,13.0,3.0,0,1,0,...,0.0,0.0,3.0,3.0,5.0,4.0,4.0,2.0,3.500000,0.916667
2583,1,"[2016-10-24 21:00:00,2016-10-24 21:20:00)",0,19.0,0,15.0,4.0,0,0,0,...,0.0,0.0,3.0,3.0,5.0,4.0,4.0,2.0,3.500000,0.916667
2584,1,"[2016-10-24 21:20:00,2016-10-24 21:40:00)",0,14.0,0,12.0,2.0,0,0,0,...,0.0,0.0,3.0,3.0,5.0,4.0,4.0,2.0,3.500000,0.916667
2585,1,"[2016-10-24 21:40:00,2016-10-24 22:00:00)",0,14.0,0,13.0,1.0,0,0,0,...,0.0,0.0,3.0,3.0,5.0,4.0,4.0,2.0,3.500000,0.916667
2586,1,"[2016-10-24 22:00:00,2016-10-24 22:20:00)",0,10.0,0,10.0,0.0,0,0,0,...,0.0,0.0,7.0,6.0,5.0,5.0,3.0,1.0,4.500000,3.916667
2587,1,"[2016-10-24 22:20:00,2016-10-24 22:40:00)",0,11.0,0,9.0,2.0,0,0,0,...,0.0,0.0,7.0,6.0,5.0,5.0,3.0,1.0,4.500000,3.916667
2588,1,"[2016-10-24 22:40:00,2016-10-24 23:00:00)",0,7.0,0,5.0,2.0,0,0,0,...,0.0,0.0,7.0,6.0,5.0,5.0,3.0,1.0,4.500000,3.916667
2589,1,"[2016-10-24 23:00:00,2016-10-24 23:20:00)",0,11.0,0,8.0,3.0,0,0,0,...,0.0,0.0,7.0,6.0,5.0,5.0,3.0,1.0,4.500000,3.916667
2590,1,"[2016-10-24 23:20:00,2016-10-24 23:40:00)",0,7.0,0,7.0,0.0,0,0,0,...,0.0,0.0,7.0,6.0,5.0,5.0,3.0,1.0,4.500000,3.916667
2591,1,"[2016-10-24 23:40:00,2016-10-25 00:00:00)",0,2.0,0,2.0,0.0,0,0,0,...,0.0,0.0,7.0,6.0,5.0,5.0,3.0,1.0,4.500000,3.916667

In [6]:
frame = [df_1_0_new,df_1_1_new,df_2_0_new,df_3_0_new,df_3_1_new]
df_full = pandas.concat(frame,ignore_index=True).drop(['time_window'],axis=1)
df_full

,tollgate_id,direction,volume,model0,model1,model2,model3,model4,model5,model6,...,type1lv_mean,type1lv_var,has_etc1lv0,has_etc1lv1,has_etc1lv2,has_etc1lv3,has_etc1lv4,has_etc1lv5,has_etc1lv_mean,has_etc1lv_var
0,1,0,13.0,0,10.0,1.0,0,0,2,0,...,0.000000,0.000000,4.0,1.0,1.0,1.0,3.0,0.0,1.666667,1.888889
1,1,0,6.0,0,6.0,0.0,0,0,0,0,...,0.000000,0.000000,4.0,1.0,1.0,1.0,3.0,0.0,1.666667,1.888889
2,1,0,9.0,0,6.0,1.0,0,1,1,0,...,0.000000,0.000000,4.0,1.0,1.0,1.0,3.0,0.0,1.666667,1.888889
3,1,0,10.0,0,7.0,0.0,0,0,3,0,...,0.000000,0.000000,4.0,1.0,1.0,1.0,3.0,0.0,1.666667,1.888889
4,1,0,14.0,1,10.0,1.0,1,0,1,0,...,0.000000,0.000000,4.0,1.0,1.0,1.0,3.0,0.0,1.666667,1.888889
5,1,0,10.0,0,9.0,0.0,0,0,1,0,...,0.000000,0.000000,4.0,1.0,1.0,1.0,3.0,0.0,1.666667,1.888889
6,1,0,7.0,0,3.0,1.0,0,1,2,0,...,0.000000,0.000000,4.0,1.0,1.0,1.0,3.0,0.0,1.666667,1.888889
7,1,0,10.0,0,3.0,5.0,0,0,2,0,...,0.000000,0.000000,4.0,1.0,1.0,1.0,3.0,0.0,1.666667,1.888889
8,1,0,6.0,0,0.0,1.0,3,1,1,0,...,0.000000,0.000000,4.0,1.0,1.0,1.0,3.0,0.0,1.666667,1.888889
9,1,0,9.0,0,5.0,2.0,0,0,2,0,...,0.000000,0.000000,4.0,1.0,1.0,1.0,3.0,0.0,1.666667,1.888889
10,1,0,4.0,0,3.0,0.0,1,0,0,0,...,0.000000,0.000000,4.0,1.0,1.0,1.0,3.0,0.0,1.666667,1.888889
11,1,0,9.0,0,5.0,1.0,2,0,1,0,...,0.000000,0.000000,4.0,1.0,1.0,1.0,3.0,0.0,1.666667,1.888889
12,1,0,10.0,0,6.0,2.0,1,0,1,0,...,0.000000,0.000000,1.0,1.0,0.0,0.0,1.0,2.0,0.833333,0.472222
13,1,0,13.0,0,9.0,2.0,1,0,1,0,...,0.000000,0.000000,1.0,1.0,0.0,0.0,1.0,2.0,0.833333,0.472222
14,1,0,12.0,0,8.0,2.0,1,0,1,0,...,0.000000,0.000000,1.0,1.0,0.0,0.0,1.0,2.0,0.833333,0.472222
15,1,0,2.0,0,0.0,2.0,0,0,0,0,...,0.000000,0.000000,1.0,1.0,0.0,0.0,1.0,2.0,0.833333,0.472222
16,1,0,8.0,0,6.0,2.0,0,0,0,0,...,0.000000,0.000000,1.0,1.0,0.0,0.0,1.0,2.0,0.833333,0.472222
17,1,0,13.0,0,12.0,1.0,0,0,0,0,...,0.000000,0.000000,1.0,1.0,0.0,0.0,1.0,2.0,0.833333,0.472222
18,1,0,8.0,0,7.0,0.0,1,0,0,0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,2.0,2.0,0.666667,0.888889
19,1,0,13.0,0,12.0,1.0,0,0,0,0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,2.0,2.0,0.666667,0.888889
20,1,0,32.0,0,28.0,2.0,1,1,0,0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,2.0,2.0,0.666667,0.888889
21,1,0,39.0,0,34.0,3.0,1,1,0,0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,2.0,2.0,0.666667,0.888889
22,1,0,31.0,0,30.0,1.0,0,0,0,0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,2.0,2.0,0.666667,0.888889
23,1,0,43.0,0,40.0,2.0,1,0,0,0,...,0.000000,0.000000,0.0,0.0,0.0,0.0,2.0,2.0,0.666667,0.888889
24,1,0,46.0,0,42.0,3.0,1,0,0,0,...,0.000000,0.000000,2.0,5.0,9.0,10.0,11.0,16.0,8.833333,19.805556
25,1,0,56.0,0,49.0,4.0,2,1,0,0,...,0.000000,0.000000,2.0,5.0,9.0,10.0,11.0,16.0,8.833333,19.805556
26,1,0,41.0,9,30.0,1.0,1,0,0,0,...,0.000000,0.000000,2.0,5.0,9.0,10.0,11.0,16.0,8.833333,19.805556
27,1,0,50.0,0,44.0,6.0,0,0,0,0,...,0.000000,0.000000,2.0,5.0,9.0,10.0,11.0,16.0,8.833333,19.805556
28,1,0,49.0,0,41.0,7.0,0,1,0,0,...,0.000000,0.000000,2.0,5.0,9.0,10.0,11.0,16.0,8.833333,19.805556
29,1,0,44.0,0,42.0,2.0,0,0,0,0,...,0.000000,0.000000,2.0,5.0,9.0,10.0,11.0,16.0,8.833333,19.805556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12930,3,1,102.0,0,93.0,7.0,0,1,1,0,...,16.500000,8.916667,13.0,20.0,18.0,19.0,25.0,22.0,19.500000,13.583333
12931,3,1,92.0,0,86.0,3.0,1,0,2,0,...,16.500000,8.916667,13.0,20.0,18.0,19.0,25.0,22.0,19.500000,13.583333
12932,3,1,92.0,0,80.0,8.0,2,1,1,0,...,16.500000,8.916667,13.0,20.0,18.0,19.0,25.0,22.0,19.500000,13.583333
12933,3,1,80.0,0,71.0,3.0,1,1,4,0,...,16.500000,8.916667,13.0,20.0,18.0,19.0,25.0,22.0,19.500000,13.583333
12934,3,1,102.0,0,94.0,3.0,1,0,4,0,...,16.500000,8.916667,13.0,20.0,18.0,19.0,25.0,22.0,19.500000,13.583333
12935,3,1,71.0,0,63.0,4.0,2,0,2,0,...,16.500000,8.916667,13.0,20.0,18.0,19.0,25.0,22.0,19.500000,13.583333
12936,3,1,101.0,0,94.0,1.0,3,0,3,0,...,13.833333,3.138889,15.0,19.0,26.0,21.0,22.0,12.0,19.166667,21.138889
12937,3,1,80.0,0,70.0,4.0,4,1,1,0,...,13.833333,3.138889,15.0,19.0,26.0,21.0,22.0,12.0,19.166667,21.138889
12938,3,1,81.0,0,69.0,7.0,3,0,2,0,...,13.833333,3.138889,15.0,19.0,26.0,21.0,22.0,12.0,19.166667,21.138889
12939,3,1,80.0,0,79.0,1.0,0,0,0,0,...,12.500000,5.583333,21.0,22.0,12.0,22.0,24.0,25.0,21.000000,18.000000
12940,3,1,97.0,0,92.0,3.0,0,0,2,0,...,12.500000,5.583333,21.0,22.0,12.0,22.0,24.0,25.0,21.000000,18.000000
12941,3,1,80.0,0,75.0,2.0,0,1,2,0,...,12.500000,5.583333,21.0,22.0,12.0,22.0,24.0,25.0,21.000000,18.000000
12942,3,1,91.0,0,83.0,4.0,0,3,1,0,...,12.500000,5.583333,21.0,22.0,12.0,22.0,24.0,25.0,21.000000,18.000000
12943,3,1,94.0,0,88.0,4.0,1,0,1,0,...,12.500000,5.583333,21.0,22.0,12.0,22.0,24.0,25.0,21.000000,18.000000
12944,3,1,74.0,0,68.0,4.0,1,1,0,0,...,12.500000,5.583333,21.0,22.0,12.0,22.0,24.0,25.0,21.000000,18.000000
12945,3,1,56.0,0,52.0,3.0,1,0,0,0,...,8.833333,13.138889,22.0,24.0,25.0,26.0,19.0,30.0,24.333333,11.555556
12946,3,1,51.0,0,45.0,3.0,1,1,1,0,...,8.833333,13.138889,22.0,24.0,25.0,26.0,19.0,30.0,24.333333,11.555556
12947,3,1,58.0,0,52.0,2.0,2,0,2,0,...,8.833333,13.138889,22.0,24.0,25.0,26.0,19.0,30.0,24.333333,11.555556
12948,3,1,35.0,0,27.0,3.0,3,1,1,0,...,7.500000,4.250000,34.0,31.0,21.0,20.0,14.0,12.0,22.000000,65.666667
12949,3,1,49.0,0,38.0,5.0,1,0,5,0,...,7.500000,4.250000,34.0,31.0,21.0,20.0,14.0,12.0,22.000000,65.666667
12950,3,1,43.0,0,36.0,3.0,0,1,3,0,...,7.500000,4.250000,34.0,31.0,21.0,20.0,14.0,12.0,22.000000,65.666667
12951,3,1,32.0,0,28.0,2.0,0,0,2,0,...,7.500000,4.250000,34.0,31.0,21.0,20.0,14.0,12.0,22.000000,65.666667
12952,3,1,38.0,0,33.0,3.0,1,0,1,0,...,7.500000,4.250000,34.0,31.0,21.0,20.0,14.0,12.0,22.000000,65.666667
12953,3,1,34.0,0,32.0,0.0,1,0,1,0,...,7.500000,4.250000,34.0,31.0,21.0,20.0,14.0,12.0,22.000000,65.666667
12954,3,1,19.0,0,16.0,1.0,0,1,1,0,...,6.500000,11.583333,9.0,11.0,11.0,11.0,7.0,6.0,9.166667,4.138889
12955,3,1,30.0,0,26.0,1.0,0,0,2,0,...,6.500000,11.583333,9.0,11.0,11.0,11.0,7.0,6.0,9.166667,4.138889
12956,3,1,33.0,0,29.0,0.0,1,1,0,1,...,6.500000,11.583333,9.0,11.0,11.0,11.0,7.0,6.0,9.166667,4.138889
12957,3,1,11.0,0,9.0,1.0,0,0,1,0,...,6.500000,11.583333,9.0,11.0,11.0,11.0,7.0,6.0,9.166667,4.138889
12958,3,1,13.0,0,13.0,0.0,0,0,0,0,...,6.500000,11.583333,9.0,11.0,11.0,11.0,7.0,6.0,9.166667,4.138889
12959,3,1,19.0,0,18.0,0.0,0,1,0,0,...,6.500000,11.583333,9.0,11.0,11.0,11.0,7.0,6.0,9.166667,4.138889

In [7]:
df_full_temp = df_full
length_full = len(df_full['time_start'])
length_filled = len(df_filled['time_start'])
for i in xrange(length_full):
    temp_full = df_full_temp['time_start'][i]
    tg_full = df_full_temp['tollgate_id'][i]
    dir_full = df_full_temp['direction'][i]
    for j in xrange(length_filled):
        if (temp_full == df_filled['time_start'][j]) and (tg_full == df_filled['tollgate_id'][j])\
                                                     and (dir_full == df_filled['direction'][j]):
            df_full_temp = df_full_temp.drop(i)
df_full_temp = df_full_temp.reset_index().drop('index',axis=1)

In [8]:
df_weather1 = pandas.read_csv("v3_weather (table 7)_training.csv")
df_weather2 = pandas.read_csv("v2_weather (table 7)_test.csv")
df_weather_temp = df_weather1.append(df_weather2, ignore_index=True)

In [9]:
df_time_temp = df_full['time_start']
df_insert_weather = preprocess_functions.insert_weather(df_full, df_time_temp, df_weather_temp)
df_add_time = preprocess_functions.add_time_dimension(df_insert_weather, df_time_temp)
df_h_judge_raw = preprocess_functions.holiday_judge(df_add_time, df_time_temp)
df_h_judge = preprocess_functions.holiday_judge_out(df_h_judge_raw, df_time_temp)
df_h_judge_new = preprocess_functions.holiday_judge_in(df_h_judge, df_time_temp)
df_final = preprocess_functions.transfer_volume(df_h_judge_new)
df_final

,tollgate_id,direction,model0,model1,model2,model3,model4,model5,model6,model7,...,humidity,month,weekday,time,hour,date,holiday_ornot,holiday_ornot_out,holiday_ornot_in,volume
0,1,0,0,10.0,1.0,0,0,2,0,0,...,76.0,9,0,0,0,19,0,0,0,13.0
1,1,0,0,6.0,0.0,0,0,0,0,0,...,76.0,9,0,1,0,19,0,0,0,6.0
2,1,0,0,6.0,1.0,0,1,1,0,0,...,76.0,9,0,2,0,19,0,0,0,9.0
3,1,0,0,7.0,0.0,0,0,3,0,0,...,76.0,9,0,3,1,19,0,0,0,10.0
4,1,0,1,10.0,1.0,1,0,1,0,0,...,76.0,9,0,4,1,19,0,0,0,14.0
5,1,0,0,9.0,0.0,0,0,1,0,0,...,76.0,9,0,5,1,19,0,0,0,10.0
6,1,0,0,3.0,1.0,0,1,2,0,0,...,76.0,9,0,6,2,19,0,0,0,7.0
7,1,0,0,3.0,5.0,0,0,2,0,0,...,76.0,9,0,7,2,19,0,0,0,10.0
8,1,0,0,0.0,1.0,3,1,1,0,0,...,76.0,9,0,8,2,19,0,0,0,6.0
9,1,0,0,5.0,2.0,0,0,2,0,0,...,67.0,9,0,9,3,19,0,0,0,9.0
10,1,0,0,3.0,0.0,1,0,0,0,0,...,67.0,9,0,10,3,19,0,0,0,4.0
11,1,0,0,5.0,1.0,2,0,1,0,0,...,67.0,9,0,11,3,19,0,0,0,9.0
12,1,0,0,6.0,2.0,1,0,1,0,0,...,67.0,9,0,12,4,19,0,0,0,10.0
13,1,0,0,9.0,2.0,1,0,1,0,0,...,67.0,9,0,13,4,19,0,0,0,13.0
14,1,0,0,8.0,2.0,1,0,1,0,0,...,67.0,9,0,14,4,19,0,0,0,12.0
15,1,0,0,0.0,2.0,0,0,0,0,0,...,67.0,9,0,15,5,19,0,0,0,2.0
16,1,0,0,6.0,2.0,0,0,0,0,0,...,67.0,9,0,16,5,19,0,0,0,8.0
17,1,0,0,12.0,1.0,0,0,0,0,0,...,67.0,9,0,17,5,19,0,0,0,13.0
18,1,0,0,7.0,0.0,1,0,0,0,0,...,56.0,9,0,18,6,19,0,0,0,8.0
19,1,0,0,12.0,1.0,0,0,0,0,0,...,56.0,9,0,19,6,19,0,0,0,13.0
20,1,0,0,28.0,2.0,1,1,0,0,0,...,56.0,9,0,20,6,19,0,0,0,32.0
21,1,0,0,34.0,3.0,1,1,0,0,0,...,56.0,9,0,21,7,19,0,0,0,39.0
22,1,0,0,30.0,1.0,0,0,0,0,0,...,56.0,9,0,22,7,19,0,0,0,31.0
23,1,0,0,40.0,2.0,1,0,0,0,0,...,56.0,9,0,23,7,19,0,0,0,43.0
24,1,0,0,42.0,3.0,1,0,0,0,0,...,56.0,9,0,24,8,19,0,0,0,46.0
25,1,0,0,49.0,4.0,2,1,0,0,0,...,56.0,9,0,25,8,19,0,0,0,56.0
26,1,0,9,30.0,1.0,1,0,0,0,0,...,56.0,9,0,26,8,19,0,0,0,41.0
27,1,0,0,44.0,6.0,0,0,0,0,0,...,72.0,9,0,27,9,19,0,0,0,50.0
28,1,0,0,41.0,7.0,0,1,0,0,0,...,72.0,9,0,28,9,19,0,0,0,49.0
29,1,0,0,42.0,2.0,0,0,0,0,0,...,72.0,9,0,29,9,19,0,0,0,44.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12930,3,1,0,93.0,7.0,0,1,1,0,0,...,81.0,10,0,42,14,24,0,0,0,102.0
12931,3,1,0,86.0,3.0,1,0,2,0,0,...,81.0,10,0,43,14,24,0,0,0,92.0
12932,3,1,0,80.0,8.0,2,1,1,0,0,...,81.0,10,0,44,14,24,0,0,0,92.0
12933,3,1,0,71.0,3.0,1,1,4,0,0,...,91.0,10,0,45,15,24,0,0,0,80.0
12934,3,1,0,94.0,3.0,1,0,4,0,0,...,91.0,10,0,46,15,24,0,0,0,102.0
12935,3,1,0,63.0,4.0,2,0,2,0,0,...,91.0,10,0,47,15,24,0,0,0,71.0
12936,3,1,0,94.0,1.0,3,0,3,0,0,...,91.0,10,0,48,16,24,0,0,0,101.0
12937,3,1,0,70.0,4.0,4,1,1,0,0,...,91.0,10,0,49,16,24,0,0,0,80.0
12938,3,1,0,69.0,7.0,3,0,2,0,0,...,91.0,10,0,50,16,24,0,0,0,81.0
12939,3,1,0,79.0,1.0,0,0,0,0,0,...,91.0,10,0,51,17,24,0,0,0,80.0
12940,3,1,0,92.0,3.0,0,0,2,0,0,...,91.0,10,0,52,17,24,0,0,0,97.0
12941,3,1,0,75.0,2.0,0,1,2,0,0,...,91.0,10,0,53,17,24,0,0,0,80.0
12942,3,1,0,83.0,4.0,0,3,1,0,0,...,94.0,10,0,54,18,24,0,0,0,91.0
12943,3,1,0,88.0,4.0,1,0,1,0,0,...,94.0,10,0,55,18,24,0,0,0,94.0
12944,3,1,0,68.0,4.0,1,1,0,0,0,...,94.0,10,0,56,18,24,0,0,0,74.0
12945,3,1,0,52.0,3.0,1,0,0,0,0,...,94.0,10,0,57,19,24,0,0,0,56.0
12946,3,1,0,45.0,3.0,1,1,1,0,0,...,94.0,10,0,58,19,24,0,0,0,51.0
12947,3,1,0,52.0,2.0,2,0,2,0,0,...,94.0,10,0,59,19,24,0,0,0,58.0
12948,3,1,0,27.0,3.0,3,1,1,0,0,...,94.0,10,0,60,20,24,0,0,0,35.0
12949,3,1,0,38.0,5.0,1,0,5,0,0,...,94.0,10,0,61,20,24,0,0,0,49.0
12950,3,1,0,36.0,3.0,0,1,3,0,0,...,94.0,10,0,62,20,24,0,0,0,43.0
12951,3,1,0,28.0,2.0,0,0,2,0,0,...,93.0,10,0,63,21,24,0,0,0,32.0
12952,3,1,0,33.0,3.0,1,0,1,0,0,...,93.0,10,0,64,21,24,0,0,0,38.0
12953,3,1,0,32.0,0.0,1,0,1,0,0,...,93.0,10,0,65,21,24,0,0,0,34.0
12954,3,1,0,16.0,1.0,0,1,1,0,0,...,93.0,10,0,66,22,24,0,0,0,19.0
12955,3,1,0,26.0,1.0,0,0,2,0,1,...,93.0,10,0,67,22,24,0,0,0,30.0
12956,3,1,0,29.0,0.0,1,1,0,1,1,...,93.0,10,0,68,22,24,0,0,0,33.0
12957,3,1,0,9.0,1.0,0,0,1,0,0,...,93.0,10,0,69,23,24,0,0,0,11.0
12958,3,1,0,13.0,0.0,0,0,0,0,0,...,93.0,10,0,70,23,24,0,0,0,13.0
12959,3,1,0,18.0,0.0,0,1,0,0,0,...,93.0,10,0,71,23,24,0,0,0,19.0

In [10]:
log_base = np.e

In [11]:
df_final['volumelv0_log'] = np.log(df_final['volumelv0'])/np.log(log_base)
df_final['volumelv1_log'] = np.log(df_final['volumelv1'])/np.log(log_base)
df_final['volumelv2_log'] = np.log(df_final['volumelv2'])/np.log(log_base)
df_final['volumelv3_log'] = np.log(df_final['volumelv3'])/np.log(log_base)
df_final['volumelv4_log'] = np.log(df_final['volumelv4'])/np.log(log_base)
df_final['volumelv5_log'] = np.log(df_final['volumelv5'])/np.log(log_base)
df_final['has_etc1lv0_log'] = np.log(df_final['has_etc1lv0']+1)/np.log(log_base)
df_final['has_etc1lv1_log'] = np.log(df_final['has_etc1lv1']+1)/np.log(log_base)
df_final['has_etc1lv2_log'] = np.log(df_final['has_etc1lv2']+1)/np.log(log_base)
df_final['has_etc1lv3_log'] = np.log(df_final['has_etc1lv3']+1)/np.log(log_base)
df_final['has_etc1lv4_log'] = np.log(df_final['has_etc1lv4']+1)/np.log(log_base)
df_final['has_etc1lv5_log'] = np.log(df_final['has_etc1lv5']+1)/np.log(log_base)
df_final['type0lv0_log'] = np.log(df_final['type0lv0']+1)/np.log(log_base)
df_final['type0lv1_log'] = np.log(df_final['type0lv1']+1)/np.log(log_base)
df_final['type0lv2_log'] = np.log(df_final['type0lv2']+1)/np.log(log_base)
df_final['type0lv3_log'] = np.log(df_final['type0lv3']+1)/np.log(log_base)
df_final['type0lv4_log'] = np.log(df_final['type0lv4']+1)/np.log(log_base)
df_final['type0lv5_log'] = np.log(df_final['type0lv5']+1)/np.log(log_base)
df_final['model1lv0_log'] = np.log(df_final['model1lv0']+1)/np.log(log_base)
df_final['model1lv1_log'] = np.log(df_final['model1lv1']+1)/np.log(log_base)
df_final['model1lv2_log'] = np.log(df_final['model1lv2']+1)/np.log(log_base)
df_final['model1lv3_log'] = np.log(df_final['model1lv3']+1)/np.log(log_base)
df_final['model1lv4_log'] = np.log(df_final['model1lv4']+1)/np.log(log_base)
df_final['model1lv5_log'] = np.log(df_final['model1lv5']+1)/np.log(log_base)

In [12]:
preprocess_functions.insert_onehot(df_final, 'tollgate_id')
preprocess_functions.insert_onehot(df_final, 'month')
preprocess_functions.insert_onehot(df_final, 'weekday')
preprocess_functions.insert_onehot(df_final, 'time')
preprocess_functions.insert_onehot(df_final, 'precipitation')
df_final

,precipitation2,precipitation1,precipitation0,time71,time70,time69,time68,time67,time66,time65,...,type0lv2_log,type0lv3_log,type0lv4_log,type0lv5_log,model1lv0_log,model1lv1_log,model1lv2_log,model1lv3_log,model1lv4_log,model1lv5_log
0,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,2.397895,1.945910,1.945910,2.079442,2.397895,2.302585
1,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,2.397895,1.945910,1.945910,2.079442,2.397895,2.302585
2,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,2.397895,1.945910,1.945910,2.079442,2.397895,2.302585
3,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,2.397895,1.945910,1.945910,2.079442,2.397895,2.302585
4,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,2.397895,1.945910,1.945910,2.079442,2.397895,2.302585
5,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,2.397895,1.945910,1.945910,2.079442,2.397895,2.302585
6,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,2.397895,1.945910,1.945910,2.079442,2.397895,2.302585
7,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,2.397895,1.945910,1.945910,2.079442,2.397895,2.302585
8,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,2.397895,1.945910,1.945910,2.079442,2.397895,2.302585
9,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,2.397895,1.945910,1.945910,2.079442,2.397895,2.302585
10,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,2.397895,1.945910,1.945910,2.079442,2.397895,2.302585
11,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,2.397895,1.945910,1.945910,2.079442,2.397895,2.302585
12,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,1.386294,1.386294,0.000000,1.791759,1.386294,1.791759
13,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,1.386294,1.386294,0.000000,1.791759,1.386294,1.791759
14,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,1.386294,1.386294,0.000000,1.791759,1.386294,1.791759
15,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,1.386294,1.386294,0.000000,1.791759,1.386294,1.791759
16,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,1.386294,1.386294,0.000000,1.791759,1.386294,1.791759
17,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,1.386294,1.386294,0.000000,1.791759,1.386294,1.791759
18,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,1.945910,2.302585,2.197225,0.000000,1.945910,2.564949
19,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,1.945910,2.302585,2.197225,0.000000,1.945910,2.564949
20,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,1.945910,2.302585,2.197225,0.000000,1.945910,2.564949
21,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,1.945910,2.302585,2.197225,0.000000,1.945910,2.564949
22,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,1.945910,2.302585,2.197225,0.000000,1.945910,2.564949
23,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,1.945910,2.302585,2.197225,0.000000,1.945910,2.564949
24,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,2.079442,2.564949,3.367296,3.555348,3.433987,3.713572
25,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,2.079442,2.564949,3.367296,3.555348,3.433987,3.713572
26,0,0,1,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,2.079442,2.564949,3.367296,3.555348,3.433987,3.713572
27,0,1,0,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,2.079442,2.564949,3.367296,3.555348,3.433987,3.713572
28,0,1,0,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,2.079442,2.564949,3.367296,3.555348,3.433987,3.713572
29,0,1,0,0,0,0,0,0,0,0,...,0.000000,0.000000,0.000000,0.000000,2.079442,2.564949,3.367296,3.555348,3.433987,3.713572
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12930,0,0,1,0,0,0,0,0,0,0,...,4.094345,4.204693,4.276666,4.127134,4.442651,4.317488,4.248495,4.262680,4.394449,4.234107
12931,0,0,1,0,0,0,0,0,0,0,...,4.094345,4.204693,4.276666,4.127134,4.442651,4.317488,4.248495,4.262680,4.394449,4.234107
12932,0,0,1,0,0,0,0,0,0,0,...,4.094345,4.204693,4.276666,4.127134,4.442651,4.317488,4.248495,4.262680,4.394449,4.234107
12933,0,0,1,0,0,0,0,0,0,0,...,4.094345,4.204693,4.276666,4.127134,4.442651,4.317488,4.248495,4.262680,4.394449,4.234107
12934,0,0,1,0,0,0,0,0,0,0,...,4.094345,4.204693,4.276666,4.127134,4.442651,4.317488,4.248495,4.262680,4.394449,4.234107
12935,0,0,1,0,0,0,0,0,0,0,...,4.094345,4.204693,4.276666,4.127134,4.442651,4.317488,4.248495,4.262680,4.394449,4.234107
12936,0,0,1,0,0,0,0,0,0,0,...,4.369448,4.219508,4.521789,4.025352,4.543295,4.465908,4.394449,4.276666,4.553877,4.158883
12937,0,0,1,0,0,0,0,0,0,0,...,4.369448,4.219508,4.521789,4.025352,4.543295,4.465908,4.394449,4.276666,4.553877,4.158883
12938,0,0,1,0,0,0,0,0,0,0,...,4.369448,4.219508,4.521789,4.025352,4.543295,4.465908,4.394449,4.276666,4.553877,4.158883
12939,0,0,1,0,0,0,0,0,0,0,...,4.025352,4.465908,4.262680,4.276666,4.276666,4.553877,4.158883,4.553877,4.262680,4.248495
12940,0,0,1,0,0,0,0,0,0,0,...,4.025352,4.465908,4.262680,4.276666,4.276666,4.553877,4.158883,4.553877,4.262680,4.248495
12941,0,0,1,0,0,0,0,0,0,0,...,4.025352,4.465908,4.262680,4.276666,4.276666,4.553877,4.158883,4.553877,4.262680,4.248495
12942,0,0,1,0,0,0,0,0,0,0,...,4.025352,4.465908,4.262680,4.276666,4.276666,4.553877,4.158883,4.553877,4.262680,4.248495
12943,0,0,1,0,0,0,0,0,0,0,...,4.025352,4.465908,4.262680,4.276666,4.276666,4.553877,4.158883,4.553877,4.262680,4.248495
12944,0,0,1,0,0,0,0,0,0,0,...,4.025352,4.465908,4.262680,4.276666,4.276666,4.553877,4.158883,4.553877,4.262680,4.248495
12945,0,0,1,0,0,0,0,0,0,0,...,4.276666,4.343805,4.532599,4.276666,4.553877,4.262680,4.248495,4.382027,4.532599,4.330733
12946,0,0,1,0,0,0,0,0,0,0,...,4.276666,4.343805,4.532599,4.276666,4.553877,4.262680,4.248495,4.382027,4.532599,4.330733
12947,0,0,1,0,0,0,0,0,0,0,...,4.276666,4.343805,4.532599,4.276666,4.553877,4.262680,4.248495,4.382027,4.532599,4.330733
12948,0,0,1,0,0,0,0,0,0,0,...,4.204693,3.970292,3.806662,3.951244,4.430817,4.488636,4.234107,3.970292,3.828641,3.970292
12949,0,0,1,0,0,0,0,0,0,0,...,4.204693,3.970292,3.806662,3.951244,4.430817,4.488636,4.234107,3.970292,3.828641,3.970292
12950,0,0,1,0,0,0,0,0,0,0,...,4.204693,3.970292,3.806662,3.951244,4.430817,4.488636,4.234107,3.970292,3.828641,3.970292
12951,0,0,1,0,0,0,0,0,0,0,...,4.204693,3.970292,3.806662,3.951244,4.430817,4.488636,4.234107,3.970292,3.828641,3.970292
12952,0,0,1,0,0,0,0,0,0,0,...,4.204693,3.970292,3.806662,3.951244,4.430817,4.488636,4.234107,3.970292,3.828641,3.970292
12953,0,0,1,0,0,0,0,0,0,1,...,4.204693,3.970292,3.806662,3.951244,4.430817,4.488636,4.234107,3.970292,3.828641,3.970292
12954,0,0,1,0,0,0,0,0,1,0,...,3.637586,3.332205,3.526361,3.496508,3.332205,3.663562,3.610918,3.367296,3.526361,3.496508
12955,0,0,1,0,0,0,0,1,0,0,...,3.637586,3.332205,3.526361,3.496508,3.332205,3.663562,3.610918,3.367296,3.526361,3.496508
12956,0,0,1,0,0,0,1,0,0,0,...,3.637586,3.332205,3.526361,3.496508,3.332205,3.663562,3.610918,3.367296,3.526361,3.496508
12957,0,0,1,0,0,1,0,0,0,0,...,3.637586,3.332205,3.526361,3.496508,3.332205,3.663562,3.610918,3.367296,3.526361,3.496508
12958,0,0,1,0,1,0,0,0,0,0,...,3.637586,3.332205,3.526361,3.496508,3.332205,3.663562,3.610918,3.367296,3.526361,3.496508
12959,0,0,1,1,0,0,0,0,0,0,...,3.637586,3.332205,3.526361,3.496508,3.332205,3.663562,3.610918,3.367296,3.526361,3.496508

In [22]:
df_final.to_csv('phase2_trainingset.csv', index=False)

# 10 KNN

In [13]:
from sklearn.model_selection import KFold
from sklearn.neighbors import KNeighborsClassifier

In [14]:
df_test_last2h = pandas.read_csv('test2_20min_avg_volume_etc_cartype.csv')
df_test_last2h
df_last2h_temp = df_test_last2h['time_window'].str.split('[',expand=True)[1].str.split(',',expand=True)[0]
df_test_last2h['time_start'] = df_last2h_temp
df_last2h_time = preprocess_functions.add_time_dimension(df_test_last2h, df_test_last2h['time_start'])
df_last2h_time['date_temp'] = df_last2h_time['time_start'].str.split('-',expand=True)[2]\
                               .str.split(' ',expand=True)[0].apply(int)
df_last2h_time

,tollgate_id,time_window,direction,volume,model0,model1,model2,model3,model4,model5,...,type0,type1,has_etc1,time_start,month,weekday,time,hour,date,date_temp
0,1,"[2016-10-25 06:00:00,2016-10-25 06:20:00)",1,37,0,26,5,2,1,2,...,21,16,5,2016-10-25 06:00:00,10,1,18,6,25,25
1,1,"[2016-10-25 06:00:00,2016-10-25 06:20:00)",0,10,0,4,6,0,0,0,...,0,0,0,2016-10-25 06:00:00,10,1,18,6,25,25
2,3,"[2016-10-25 06:00:00,2016-10-25 06:20:00)",1,30,0,19,5,2,1,3,...,13,17,4,2016-10-25 06:00:00,10,1,18,6,25,25
3,3,"[2016-10-25 06:00:00,2016-10-25 06:20:00)",0,28,0,21,7,0,0,0,...,0,0,3,2016-10-25 06:00:00,10,1,18,6,25,25
4,2,"[2016-10-25 06:00:00,2016-10-25 06:20:00)",0,29,0,21,8,0,0,0,...,0,0,11,2016-10-25 06:00:00,10,1,18,6,25,25
5,1,"[2016-10-25 06:20:00,2016-10-25 06:40:00)",1,54,0,39,10,1,0,4,...,30,24,5,2016-10-25 06:20:00,10,1,19,6,25,25
6,1,"[2016-10-25 06:20:00,2016-10-25 06:40:00)",0,17,0,13,4,0,0,0,...,0,0,3,2016-10-25 06:20:00,10,1,19,6,25,25
7,3,"[2016-10-25 06:20:00,2016-10-25 06:40:00)",1,31,0,16,9,3,1,2,...,14,17,5,2016-10-25 06:20:00,10,1,19,6,25,25
8,3,"[2016-10-25 06:20:00,2016-10-25 06:40:00)",0,48,0,34,12,0,2,0,...,0,0,14,2016-10-25 06:20:00,10,1,19,6,25,25
9,2,"[2016-10-25 06:20:00,2016-10-25 06:40:00)",0,27,0,20,7,0,0,0,...,0,0,3,2016-10-25 06:20:00,10,1,19,6,25,25
10,1,"[2016-10-25 06:40:00,2016-10-25 07:00:00)",1,63,0,45,10,4,1,3,...,33,30,15,2016-10-25 06:40:00,10,1,20,6,25,25
11,1,"[2016-10-25 06:40:00,2016-10-25 07:00:00)",0,30,0,20,6,3,1,0,...,0,0,8,2016-10-25 06:40:00,10,1,20,6,25,25
12,3,"[2016-10-25 06:40:00,2016-10-25 07:00:00)",1,42,0,34,3,2,1,2,...,24,18,14,2016-10-25 06:40:00,10,1,20,6,25,25
13,3,"[2016-10-25 06:40:00,2016-10-25 07:00:00)",0,92,0,75,11,2,4,0,...,0,0,26,2016-10-25 06:40:00,10,1,20,6,25,25
14,2,"[2016-10-25 06:40:00,2016-10-25 07:00:00)",0,40,0,35,5,0,0,0,...,0,0,13,2016-10-25 06:40:00,10,1,20,6,25,25
15,1,"[2016-10-25 07:00:00,2016-10-25 07:20:00)",1,67,0,57,7,1,1,1,...,52,15,17,2016-10-25 07:00:00,10,1,21,7,25,25
16,1,"[2016-10-25 07:00:00,2016-10-25 07:20:00)",0,25,0,21,3,0,1,0,...,0,0,6,2016-10-25 07:00:00,10,1,21,7,25,25
17,3,"[2016-10-25 07:00:00,2016-10-25 07:20:00)",1,62,0,50,7,1,0,4,...,45,17,16,2016-10-25 07:00:00,10,1,21,7,25,25
18,3,"[2016-10-25 07:00:00,2016-10-25 07:20:00)",0,129,0,109,14,1,5,0,...,0,0,44,2016-10-25 07:00:00,10,1,21,7,25,25
19,2,"[2016-10-25 07:00:00,2016-10-25 07:20:00)",0,83,0,76,6,0,1,0,...,0,0,37,2016-10-25 07:00:00,10,1,21,7,25,25
20,1,"[2016-10-25 07:20:00,2016-10-25 07:40:00)",1,99,0,83,7,4,2,3,...,80,19,29,2016-10-25 07:20:00,10,1,22,7,25,25
21,1,"[2016-10-25 07:20:00,2016-10-25 07:40:00)",0,38,0,34,4,0,0,0,...,0,0,14,2016-10-25 07:20:00,10,1,22,7,25,25
22,3,"[2016-10-25 07:20:00,2016-10-25 07:40:00)",1,89,0,77,8,2,1,1,...,67,22,21,2016-10-25 07:20:00,10,1,22,7,25,25
23,3,"[2016-10-25 07:20:00,2016-10-25 07:40:00)",0,131,0,113,16,1,1,0,...,0,0,49,2016-10-25 07:20:00,10,1,22,7,25,25
24,2,"[2016-10-25 07:20:00,2016-10-25 07:40:00)",0,98,0,91,5,1,1,0,...,0,0,43,2016-10-25 07:20:00,10,1,22,7,25,25
25,1,"[2016-10-25 07:40:00,2016-10-25 08:00:00)",1,133,0,118,7,4,1,3,...,107,26,39,2016-10-25 07:40:00,10,1,23,7,25,25
26,1,"[2016-10-25 07:40:00,2016-10-25 08:00:00)",0,44,0,42,1,1,0,0,...,0,0,14,2016-10-25 07:40:00,10,1,23,7,25,25
27,3,"[2016-10-25 07:40:00,2016-10-25 08:00:00)",1,84,0,77,5,0,0,0,...,76,8,25,2016-10-25 07:40:00,10,1,23,7,25,25
28,3,"[2016-10-25 07:40:00,2016-10-25 08:00:00)",0,139,0,117,17,1,4,0,...,0,0,44,2016-10-25 07:40:00,10,1,23,7,25,25
29,2,"[2016-10-25 07:40:00,2016-10-25 08:00:00)",0,93,0,91,2,0,0,0,...,0,0,38,2016-10-25 07:40:00,10,1,23,7,25,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,1,"[2016-10-31 15:00:00,2016-10-31 15:20:00)",1,96,0,92,3,0,0,1,...,82,14,24,2016-10-31 15:00:00,10,0,45,15,31,31
391,1,"[2016-10-31 15:00:00,2016-10-31 15:20:00)",0,94,0,85,5,0,0,4,...,0,0,10,2016-10-31 15:00:00,10,0,45,15,31,31
392,3,"[2016-10-31 15:00:00,2016-10-31 15:20:00)",1,80,0,71,8,0,0,1,...,69,11,23,2016-10-31 15:00:00,10,0,45,15,31,31
393,3,"[2016-10-31 15:00:00,2016-10-31 15:20:00)",0,111,0,82,25,1,3,0,...,0,0,27,2016-10-31 15:00:00,10,0,45,15,31,31
394,2,"[2016-10-31 15:00:00,2016-10-31 15:20:00)",0,13,0,12,0,0,1,0,...,0,0,13,2016-10-31 15:00:00,10,0,45,15,31,31
395,1,"[2016-10-31 15:20:00,2016-10-31 15:40:00)",1,101,0,88,8,3,0,2,...,78,23,19,2016-10-31 15:20:00,10,0,46,15,31,31
396,1,"[2016-10-31 15:20:00,2016-10-31 15:40:00)",0,94,0,83,4,1,0,6,...,0,0,9,2016-10-31 15:20:00,10,0,46,15,31,31
397,3,"[2016-10-31 15:20:00,2016-10-31 15:40:00)",1,90,0,81,6,1,1,1,...,75,15,20,2016-10-31 15:20:00,10,0,46,15,31,31
398,3,"[2016-10-31 15:20:00,2016-10-31 15:40:00)",0,97,0,81,14,1,1,0,...,0,0,28,2016-10-31 15:20:00,10,0,46,15,31,31
399,2,"[2016-10-31 15:20:00,2016-10-31 15:40:00)",0,17,0,16,1,0,0,0,...,0,0,17,2016-10-31 15:20:00,10,0,46,15,31,31
400,1,"[2016-10-31 15:40:00,2016-10-31 16:00:00)",1,106,0,90,4,3,6,3,...,78,28,24,2016-10-31 15:40:00,10,0,47,15,31,31
401,1,"[2016-10-31 15:40:00,2016-10-31 16:00:00)",0,88,0,81,3,1,0,3,...,0,0,14,2016-10-31 15:40:00,10,0,47,15,31,31
402,3,"[2016-10-31 15:40:00,2016-10-31 16:00:00)",1,81,0,70,5,3,0,2,...,65,16,20,2016-10-31 15:40:00,10,0,47,15,31,31
403,3,"[2016-10-31 15:40:00,2016-10-31 16:00:00)",0,94,0,74,20,0,0,0,...,0,0,25,2016-10-31 15:40:00,10,0,47,15,31,31
404,2,"[2016-10-31 15:40:00,2016-10-31 16:00:00)",0,13,0,13,0,0,0,0,...,0,0,13,2016-10-31 15:40:00,10,0,47,15,31,31
405,1,"[2016-10-31 16:00:00,2016-10-31 16:20:00)",1,96,0,86,5,1,0,3,...,76,20,20,2016-10-31 16:00:00,10,0,48,16,31,31
406,1,"[2016-10-31 16:00:00,2016-10-31 16:20:00)",0,85,0,73,10,1,0,1,...,0,0,7,2016-10-31 16:00:00,10,0,48,16,31,31
407,3,"[2016-10-31 16:00:00,2016-10-31 16:20:00)",1,73,0,67,3,1,0,2,...,65,8,26,2016-10-31 16:00:00,10,0,48,16,31,31
408,3,"[2016-10-31 16:00:00,2016-10-31 16:20:00)",0,128,0,97,28,0,3,0,...,0,0,31,2016-10-31 16:00:00,10,0,48,16,31,31
409,2,"[2016-10-31 16:00:00,2016-10-31 16:20:00)",0,19,0,19,0,0,0,0,...,0,0,19,2016-10-31 16:00:00,10,0,48,16,31,31
410,1,"[2016-10-31 16:20:00,2016-10-31 16:40:00)",1,107,0,97,6,1,1,2,...,92,15,28,2016-10-31 16:20:00,10,0,49,16,31,31
411,1,"[2016-10-31 16:20:00,2016-10-31 16:40:00)",0,93,0,80,6,0,1,6,...,0,0,13,2016-10-31 16:20:00,10,0,49,16,31,31
412,3,"[2016-10-31 16:20:00,2016-10-31 16:40:00)",1,92,0,84,4,3,0,1,...,82,10,24,2016-10-31 16:20:00,10,0,49,16,31,31
413,3,"[2016-10-31 16:20:00,2016-10-31 16:40:00)",0,108,0,84,22,2,0,0,...,0,0,28,2016-10-31 16:20:00,10,0,49,16,31,31
414,2,"[2016-10-31 16:20:00,2016-10-31 16:40:00)",0,12,0,12,0,0,0,0,...,0,0,12,2016-10-31 16:20:00,10,0,49,16,31,31
415,1,"[2016-10-31 16:40:00,2016-10-31 17:00:00)",1,99,0,88,9,1,1,0,...,82,17,23,2016-10-31 16:40:00,10,0,50,16,31,31
416,1,"[2016-10-31 16:40:00,2016-10-31 17:00:00)",0,88,0,81,5,0,0,2,...,0,0,7,2016-10-31 16:40:00,10,0,50,16,31,31
417,3,"[2016-10-31 16:40:00,2016-10-31 17:00:00)",1,68,0,60,3,1,1,3,...,57,11,19,2016-10-31 16:40:00,10,0,50,16,31,31
418,3,"[2016-10-31 16:40:00,2016-10-31 17:00:00)",0,104,0,89,13,0,2,0,...,0,0,35,2016-10-31 16:40:00,10,0,50,16,31,31
419,2,"[2016-10-31 16:40:00,2016-10-31 17:00:00)",0,17,0,14,2,1,0,0,...,0,0,17,2016-10-31 16:40:00,10,0,50,16,31,31

In [15]:
df_last2h_time_10 = df_last2h_time[(df_last2h_time['tollgate_id']==1) & (df_last2h_time['direction']==0)]
df_last2h_time_11 = df_last2h_time[(df_last2h_time['tollgate_id']==1) & (df_last2h_time['direction']==1)]
df_last2h_time_20 = df_last2h_time[(df_last2h_time['tollgate_id']==2) & (df_last2h_time['direction']==0)]
df_last2h_time_30 = df_last2h_time[(df_last2h_time['tollgate_id']==3) & (df_last2h_time['direction']==0)]
df_last2h_time_31 = df_last2h_time[(df_last2h_time['tollgate_id']==3) & (df_last2h_time['direction']==1)]
df_last2h_time_10

,tollgate_id,time_window,direction,volume,model0,model1,model2,model3,model4,model5,...,type0,type1,has_etc1,time_start,month,weekday,time,hour,date,date_temp
1,1,"[2016-10-25 06:00:00,2016-10-25 06:20:00)",0,10,0,4,6,0,0,0,...,0,0,0,2016-10-25 06:00:00,10,1,18,6,25,25
6,1,"[2016-10-25 06:20:00,2016-10-25 06:40:00)",0,17,0,13,4,0,0,0,...,0,0,3,2016-10-25 06:20:00,10,1,19,6,25,25
11,1,"[2016-10-25 06:40:00,2016-10-25 07:00:00)",0,30,0,20,6,3,1,0,...,0,0,8,2016-10-25 06:40:00,10,1,20,6,25,25
16,1,"[2016-10-25 07:00:00,2016-10-25 07:20:00)",0,25,0,21,3,0,1,0,...,0,0,6,2016-10-25 07:00:00,10,1,21,7,25,25
21,1,"[2016-10-25 07:20:00,2016-10-25 07:40:00)",0,38,0,34,4,0,0,0,...,0,0,14,2016-10-25 07:20:00,10,1,22,7,25,25
26,1,"[2016-10-25 07:40:00,2016-10-25 08:00:00)",0,44,0,42,1,1,0,0,...,0,0,14,2016-10-25 07:40:00,10,1,23,7,25,25
31,1,"[2016-10-25 15:00:00,2016-10-25 15:20:00)",0,52,0,47,5,0,0,0,...,0,0,18,2016-10-25 15:00:00,10,1,45,15,25,25
36,1,"[2016-10-25 15:20:00,2016-10-25 15:40:00)",0,44,0,43,1,0,0,0,...,0,0,11,2016-10-25 15:20:00,10,1,46,15,25,25
41,1,"[2016-10-25 15:40:00,2016-10-25 16:00:00)",0,46,0,38,8,0,0,0,...,0,0,13,2016-10-25 15:40:00,10,1,47,15,25,25
46,1,"[2016-10-25 16:00:00,2016-10-25 16:20:00)",0,50,0,49,1,0,0,0,...,0,0,13,2016-10-25 16:00:00,10,1,48,16,25,25
51,1,"[2016-10-25 16:20:00,2016-10-25 16:40:00)",0,40,0,38,1,0,1,0,...,0,0,10,2016-10-25 16:20:00,10,1,49,16,25,25
56,1,"[2016-10-25 16:40:00,2016-10-25 17:00:00)",0,50,0,49,1,0,0,0,...,0,0,10,2016-10-25 16:40:00,10,1,50,16,25,25
61,1,"[2016-10-26 06:00:00,2016-10-26 06:20:00)",0,12,0,8,4,0,0,0,...,0,0,3,2016-10-26 06:00:00,10,2,18,6,26,26
66,1,"[2016-10-26 06:20:00,2016-10-26 06:40:00)",0,9,0,7,2,0,0,0,...,0,0,1,2016-10-26 06:20:00,10,2,19,6,26,26
71,1,"[2016-10-26 06:40:00,2016-10-26 07:00:00)",0,25,0,17,5,2,1,0,...,0,0,6,2016-10-26 06:40:00,10,2,20,6,26,26
76,1,"[2016-10-26 07:00:00,2016-10-26 07:20:00)",0,31,0,24,6,0,1,0,...,0,0,7,2016-10-26 07:00:00,10,2,21,7,26,26
81,1,"[2016-10-26 07:20:00,2016-10-26 07:40:00)",0,32,0,27,5,0,0,0,...,0,0,10,2016-10-26 07:20:00,10,2,22,7,26,26
86,1,"[2016-10-26 07:40:00,2016-10-26 08:00:00)",0,45,0,40,5,0,0,0,...,0,0,13,2016-10-26 07:40:00,10,2,23,7,26,26
91,1,"[2016-10-26 15:00:00,2016-10-26 15:20:00)",0,38,0,35,3,0,0,0,...,0,0,7,2016-10-26 15:00:00,10,2,45,15,26,26
96,1,"[2016-10-26 15:20:00,2016-10-26 15:40:00)",0,36,0,33,3,0,0,0,...,0,0,8,2016-10-26 15:20:00,10,2,46,15,26,26
101,1,"[2016-10-26 15:40:00,2016-10-26 16:00:00)",0,44,0,42,2,0,0,0,...,0,0,14,2016-10-26 15:40:00,10,2,47,15,26,26
106,1,"[2016-10-26 16:00:00,2016-10-26 16:20:00)",0,49,0,43,6,0,0,0,...,0,0,13,2016-10-26 16:00:00,10,2,48,16,26,26
111,1,"[2016-10-26 16:20:00,2016-10-26 16:40:00)",0,45,0,41,4,0,0,0,...,0,0,11,2016-10-26 16:20:00,10,2,49,16,26,26
116,1,"[2016-10-26 16:40:00,2016-10-26 17:00:00)",0,46,0,44,1,0,1,0,...,0,0,11,2016-10-26 16:40:00,10,2,50,16,26,26
121,1,"[2016-10-27 06:00:00,2016-10-27 06:20:00)",0,14,0,10,4,0,0,0,...,0,0,1,2016-10-27 06:00:00,10,3,18,6,27,27
126,1,"[2016-10-27 06:20:00,2016-10-27 06:40:00)",0,14,0,11,3,0,0,0,...,0,0,3,2016-10-27 06:20:00,10,3,19,6,27,27
131,1,"[2016-10-27 06:40:00,2016-10-27 07:00:00)",0,23,0,18,2,2,1,0,...,0,0,8,2016-10-27 06:40:00,10,3,20,6,27,27
136,1,"[2016-10-27 07:00:00,2016-10-27 07:20:00)",0,20,0,15,3,0,2,0,...,0,0,7,2016-10-27 07:00:00,10,3,21,7,27,27
141,1,"[2016-10-27 07:20:00,2016-10-27 07:40:00)",0,36,0,30,6,0,0,0,...,0,0,13,2016-10-27 07:20:00,10,3,22,7,27,27
146,1,"[2016-10-27 07:40:00,2016-10-27 08:00:00)",0,42,0,40,2,0,0,0,...,0,0,11,2016-10-27 07:40:00,10,3,23,7,27,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,1,"[2016-10-29 15:00:00,2016-10-29 15:20:00)",0,60,0,54,5,1,0,0,...,0,0,10,2016-10-29 15:00:00,10,5,45,15,29,29
276,1,"[2016-10-29 15:20:00,2016-10-29 15:40:00)",0,48,0,40,5,2,1,0,...,0,0,13,2016-10-29 15:20:00,10,5,46,15,29,29
281,1,"[2016-10-29 15:40:00,2016-10-29 16:00:00)",0,52,0,48,3,1,0,0,...,0,0,11,2016-10-29 15:40:00,10,5,47,15,29,29
286,1,"[2016-10-29 16:00:00,2016-10-29 16:20:00)",0,48,0,46,1,1,0,0,...,0,0,15,2016-10-29 16:00:00,10,5,48,16,29,29
291,1,"[2016-10-29 16:20:00,2016-10-29 16:40:00)",0,62,0,58,2,0,2,0,...,0,0,18,2016-10-29 16:20:00,10,5,49,16,29,29
296,1,"[2016-10-29 16:40:00,2016-10-29 17:00:00)",0,48,0,44,4,0,0,0,...,0,0,9,2016-10-29 16:40:00,10,5,50,16,29,29
301,1,"[2016-10-30 06:00:00,2016-10-30 06:20:00)",0,18,0,8,5,0,1,4,...,0,0,1,2016-10-30 06:00:00,10,6,18,6,30,30
306,1,"[2016-10-30 06:20:00,2016-10-30 06:40:00)",0,25,0,17,7,0,0,1,...,0,0,2,2016-10-30 06:20:00,10,6,19,6,30,30
311,1,"[2016-10-30 06:40:00,2016-10-30 07:00:00)",0,30,0,23,3,2,0,2,...,0,0,5,2016-10-30 06:40:00,10,6,20,6,30,30
316,1,"[2016-10-30 07:00:00,2016-10-30 07:20:00)",0,49,0,44,3,2,0,0,...,0,0,6,2016-10-30 07:00:00,10,6,21,7,30,30
321,1,"[2016-10-30 07:20:00,2016-10-30 07:40:00)",0,40,0,37,2,0,1,0,...,0,0,4,2016-10-30 07:20:00,10,6,22,7,30,30
326,1,"[2016-10-30 07:40:00,2016-10-30 08:00:00)",0,74,0,67,3,1,1,2,...,0,0,10,2016-10-30 07:40:00,10,6,23,7,30,30
331,1,"[2016-10-30 15:00:00,2016-10-30 15:20:00)",0,122,0,114,2,1,2,3,...,0,0,17,2016-10-30 15:00:00,10,6,45,15,30,30
336,1,"[2016-10-30 15:20:00,2016-10-30 15:40:00)",0,129,0,125,1,1,0,2,...,0,0,18,2016-10-30 15:20:00,10,6,46,15,30,30
341,1,"[2016-10-30 15:40:00,2016-10-30 16:00:00)",0,152,0,137,10,1,1,3,...,0,0,19,2016-10-30 15:40:00,10,6,47,15,30,30
346,1,"[2016-10-30 16:00:00,2016-10-30 16:20:00)",0,118,0,111,4,1,1,1,...,0,0,19,2016-10-30 16:00:00,10,6,48,16,30,30
351,1,"[2016-10-30 16:20:00,2016-10-30 16:40:00)",0,112,0,102,5,1,1,3,...,0,0,21,2016-10-30 16:20:00,10,6,49,16,30,30
356,1,"[2016-10-30 16:40:00,2016-10-30 17:00:00)",0,110,0,106,3,0,0,1,...,0,0,12,2016-10-30 16:40:00,10,6,50,16,30,30
361,1,"[2016-10-31 06:00:00,2016-10-31 06:20:00)",0,27,0,23,3,0,0,1,...,0,0,2,2016-10-31 06:00:00,10,0,18,6,31,31
366,1,"[2016-10-31 06:20:00,2016-10-31 06:40:00)",0,54,0,47,7,0,0,0,...,0,0,5,2016-10-31 06:20:00,10,0,19,6,31,31
371,1,"[2016-10-31 06:40:00,2016-10-31 07:00:00)",0,60,0,54,4,2,0,0,...,0,0,8,2016-10-31 06:40:00,10,0,20,6,31,31
376,1,"[2016-10-31 07:00:00,2016-10-31 07:20:00)",0,95,0,89,2,1,3,0,...,0,0,8,2016-10-31 07:00:00,10,0,21,7,31,31
381,1,"[2016-10-31 07:20:00,2016-10-31 07:40:00)",0,98,0,91,5,1,0,1,...,0,0,16,2016-10-31 07:20:00,10,0,22,7,31,31
386,1,"[2016-10-31 07:40:00,2016-10-31 08:00:00)",0,106,0,102,4,0,0,0,...,0,0,15,2016-10-31 07:40:00,10,0,23,7,31,31
391,1,"[2016-10-31 15:00:00,2016-10-31 15:20:00)",0,94,0,85,5,0,0,4,...,0,0,10,2016-10-31 15:00:00,10,0,45,15,31,31
396,1,"[2016-10-31 15:20:00,2016-10-31 15:40:00)",0,94,0,83,4,1,0,6,...,0,0,9,2016-10-31 15:20:00,10,0,46,15,31,31
401,1,"[2016-10-31 15:40:00,2016-10-31 16:00:00)",0,88,0,81,3,1,0,3,...,0,0,14,2016-10-31 15:40:00,10,0,47,15,31,31
406,1,"[2016-10-31 16:00:00,2016-10-31 16:20:00)",0,85,0,73,10,1,0,1,...,0,0,7,2016-10-31 16:00:00,10,0,48,16,31,31
411,1,"[2016-10-31 16:20:00,2016-10-31 16:40:00)",0,93,0,80,6,0,1,6,...,0,0,13,2016-10-31 16:20:00,10,0,49,16,31,31
416,1,"[2016-10-31 16:40:00,2016-10-31 17:00:00)",0,88,0,81,5,0,0,2,...,0,0,7,2016-10-31 16:40:00,10,0,50,16,31,31

In [16]:
predict_list_10m = []
predict_list_11m = []
predict_list_20m = []
predict_list_30m = []
predict_list_31m = []

for i in xrange(7):
    df_last2h_date_10m = df_last2h_time_10[(df_last2h_time_10['date_temp'] == (25+i)) & (df_last2h_time_10['time']<24)]\
                                .sort_values(['time','tollgate_id','direction']).reset_index().drop(['index'],axis=1)
    predict_list_10m.append(list(df_last2h_date_10m['volume']))
for i in xrange(7):
    df_last2h_date_11m = df_last2h_time_11[(df_last2h_time_11['date_temp'] == (25+i)) & (df_last2h_time_11['time']<24)]\
                                .sort_values(['time','tollgate_id','direction']).reset_index().drop(['index'],axis=1)
    predict_list_11m.append(list(df_last2h_date_11m['volume']))
for i in xrange(7):
    df_last2h_date_20m = df_last2h_time_20[(df_last2h_time_20['date_temp'] == (25+i)) & (df_last2h_time_20['time']<24)]\
                                .sort_values(['time','tollgate_id','direction']).reset_index().drop(['index'],axis=1)
    predict_list_20m.append(list(df_last2h_date_20m['volume']))
for i in xrange(7):
    df_last2h_date_30m = df_last2h_time_30[(df_last2h_time_30['date_temp'] == (25+i)) & (df_last2h_time_30['time']<24)]\
                                .sort_values(['time','tollgate_id','direction']).reset_index().drop(['index'],axis=1)
    predict_list_30m.append(list(df_last2h_date_30m['volume']))
for i in xrange(7):
    df_last2h_date_31m = df_last2h_time_31[(df_last2h_time_31['date_temp'] == (25+i)) & (df_last2h_time_31['time']<24)]\
                                .sort_values(['time','tollgate_id','direction']).reset_index().drop(['index'],axis=1)
    predict_list_31m.append(list(df_last2h_date_31m['volume']))
predict_list_10m

[[10, 17, 30, 25, 38, 44],
 [12, 9, 25, 31, 32, 45],
 [14, 14, 23, 20, 36, 42],
 [8, 21, 14, 28, 37, 46],
 [11, 17, 19, 27, 37, 24],
 [18, 25, 30, 49, 40, 74],
 [27, 54, 60, 95, 98, 106]]

In [17]:
predict_list_10a = []
predict_list_11a = []
predict_list_20a = []
predict_list_30a = []
predict_list_31a = []

for i in xrange(7):
    df_last2h_date_10a = df_last2h_time_10[(df_last2h_time_10['date_temp'] == (25+i)) & (df_last2h_time_10['time']>24)]\
                                .sort_values(['time','tollgate_id','direction']).reset_index().drop(['index'],axis=1)
    predict_list_10a.append(list(df_last2h_date_10a['volume']))
for i in xrange(7):
    df_last2h_date_11a = df_last2h_time_11[(df_last2h_time_11['date_temp'] == (25+i)) & (df_last2h_time_11['time']>24)]\
                                .sort_values(['time','tollgate_id','direction']).reset_index().drop(['index'],axis=1)
    predict_list_11a.append(list(df_last2h_date_11a['volume']))
for i in xrange(7):
    df_last2h_date_20a = df_last2h_time_20[(df_last2h_time_20['date_temp'] == (25+i)) & (df_last2h_time_20['time']>24)]\
                                .sort_values(['time','tollgate_id','direction']).reset_index().drop(['index'],axis=1)
    predict_list_20a.append(list(df_last2h_date_20a['volume']))
for i in xrange(7):
    df_last2h_date_30a = df_last2h_time_30[(df_last2h_time_30['date_temp'] == (25+i)) & (df_last2h_time_30['time']>24)]\
                                .sort_values(['time','tollgate_id','direction']).reset_index().drop(['index'],axis=1)
    predict_list_30a.append(list(df_last2h_date_30a['volume']))
for i in xrange(7):
    df_last2h_date_31a = df_last2h_time_31[(df_last2h_time_31['date_temp'] == (25+i)) & (df_last2h_time_31['time']>24)]\
                                .sort_values(['time','tollgate_id','direction']).reset_index().drop(['index'],axis=1)
    predict_list_31a.append(list(df_last2h_date_31a['volume']))
predict_list_10a

[[52, 44, 46, 50, 40, 50],
 [38, 36, 44, 49, 45, 46],
 [40, 37, 45, 49, 41, 45],
 [62, 48, 57, 78, 67, 58],
 [60, 48, 52, 48, 62, 48],
 [122, 129, 152, 118, 112, 110],
 [94, 94, 88, 85, 93, 88]]

In [19]:
df_final['date_temp'] = df_final['time_start'].str.split('-',expand=True)[2]\
                               .str.split(' ',expand=True)[0].apply(int)
d10 = df_final[(df_final['tollgate_id']==1) & (df_final['direction']==0)]
d11 = df_final[(df_final['tollgate_id']==1) & (df_final['direction']==1)]
d20 = df_final[(df_final['tollgate_id']==2) & (df_final['direction']==0)]
d30 = df_final[(df_final['tollgate_id']==3) & (df_final['direction']==0)]
d31 = df_final[(df_final['tollgate_id']==3) & (df_final['direction']==1)]

knn_training_list_10m = []
knn_training_list_11m = []
knn_training_list_20m = []
knn_training_list_30m = []
knn_training_list_31m = []

knn_training_list_10a = []
knn_training_list_11a = []
knn_training_list_20a = []
knn_training_list_30a = []
knn_training_list_31a = []

#morning
for i in xrange(12):
    df_last2h_date_10m = d10[(d10['date_temp'] == (19+i)) & (d10['month'] == 9) & (d10['time'] > 17) &\
                               (d10['time'] < 24) ]\
                               .sort_values(['time','tollgate_id','direction'])\
                               .reset_index().drop(['index'],axis=1)
    knn_training_list_10m.append(list(df_last2h_date_10m['volume']))
for i in xrange(17):
    df_last2h_date_10m = d10[(d10['date_temp'] == (8+i)) & (d10['month'] == 10) & (d10['time'] > 17) &\
                               (d10['time'] < 24)]\
                               .sort_values(['time','tollgate_id','direction'])\
                               .reset_index().drop(['index'],axis=1)
    knn_training_list_10m.append(list(df_last2h_date_10m['volume']))
    
for i in xrange(12):
    df_last2h_date_11m = d11[(d11['date_temp'] == (19+i)) & (d11['month'] == 9) & (d11['time'] > 17) &\
                               (d11['time'] < 24)]\
                               .sort_values(['time','tollgate_id','direction'])\
                               .reset_index().drop(['index'],axis=1)
    knn_training_list_11m.append(list(df_last2h_date_11m['volume']))
for i in xrange(17):
    df_last2h_date_11m = d11[(d11['date_temp'] == (8+i)) & (d11['month'] == 10) & (d11['time'] > 17) &\
                               (d11['time'] < 24)]\
                               .sort_values(['time','tollgate_id','direction'])\
                               .reset_index().drop(['index'],axis=1)
    knn_training_list_11m.append(list(df_last2h_date_11m['volume']))
    
for i in xrange(12):
    df_last2h_date_20m = d20[(d20['date_temp'] == (19+i)) & (d20['month'] == 9) & (d20['time'] > 17) &\
                               (d20['time'] < 24)]\
                               .sort_values(['time','tollgate_id','direction'])\
                               .reset_index().drop(['index'],axis=1)
    knn_training_list_20m.append(list(df_last2h_date_20m['volume']))
for i in xrange(17):
    df_last2h_date_20m = d20[(d20['date_temp'] == (8+i)) & (d20['month'] == 10) & (d20['time'] > 17) &\
                               (d20['time'] < 24)]\
                               .sort_values(['time','tollgate_id','direction'])\
                               .reset_index().drop(['index'],axis=1)
    knn_training_list_20m.append(list(df_last2h_date_20m['volume']))
    
for i in xrange(12):
    df_last2h_date_30m = d30[(d30['date_temp'] == (19+i)) & (d30['month'] == 9) & (d30['time'] > 17) &\
                               (d30['time'] < 24)]\
                               .sort_values(['time','tollgate_id','direction'])\
                               .reset_index().drop(['index'],axis=1)
    knn_training_list_30m.append(list(df_last2h_date_30m['volume']))
for i in xrange(17):
    df_last2h_date_30m = d30[(d30['date_temp'] == (8+i)) & (d30['month'] == 10) & (d30['time'] > 17) &\
                               (d30['time'] < 24)]\
                               .sort_values(['time','tollgate_id','direction'])\
                               .reset_index().drop(['index'],axis=1)
    knn_training_list_30m.append(list(df_last2h_date_30m['volume'])) 

for i in xrange(12):
    df_last2h_date_31m = d31[(d31['date_temp'] == (19+i)) & (d31['month'] == 9) & (d31['time'] > 17) &\
                               (d31['time'] < 24)]\
                               .sort_values(['time','tollgate_id','direction'])\
                               .reset_index().drop(['index'],axis=1)
    knn_training_list_31m.append(list(df_last2h_date_31m['volume']))
for i in xrange(17):
    df_last2h_date_31m = d31[(d31['date_temp'] == (8+i)) & (d31['month'] == 10) & (d31['time'] > 17) &\
                               (d31['time'] < 24)]\
                               .sort_values(['time','tollgate_id','direction'])\
                               .reset_index().drop(['index'],axis=1)
    knn_training_list_31m.append(list(df_last2h_date_31m['volume']))
    
#afternoon
for i in xrange(12):
    df_last2h_date_10a = d10[(d10['date_temp'] == (19+i)) & (d10['month'] == 9) 
                               & (d10['time'] > 44) & (d10['time'] < 51)]\
                               .sort_values(['time','tollgate_id','direction'])\
                               .reset_index().drop(['index'],axis=1)
    knn_training_list_10a.append(list(df_last2h_date_10a['volume']))
for i in xrange(17):
    df_last2h_date_10a = d10[(d10['date_temp'] == (8+i)) & (d10['month'] == 10) 
                               & (d10['time'] > 44) & (d10['time'] < 51)]\
                               .sort_values(['time','tollgate_id','direction'])\
                               .reset_index().drop(['index'],axis=1)
    knn_training_list_10a.append(list(df_last2h_date_10a['volume']))
    
for i in xrange(12):
    df_last2h_date_11a = d11[(d11['date_temp'] == (19+i)) & (d11['month'] == 9)
                               & (d11['time'] > 44) & (d11['time'] < 51)]\
                               .sort_values(['time','tollgate_id','direction'])\
                               .reset_index().drop(['index'],axis=1)
    knn_training_list_11a.append(list(df_last2h_date_11a['volume']))
for i in xrange(17):
    df_last2h_date_11a = d11[(d11['date_temp'] == (8+i)) & (d11['month'] == 10) 
                               & (d11['time'] > 44) & (d11['time'] < 51)]\
                               .sort_values(['time','tollgate_id','direction'])\
                               .reset_index().drop(['index'],axis=1)
    knn_training_list_11a.append(list(df_last2h_date_11a['volume']))
    
for i in xrange(12):
    df_last2h_date_20a = d20[(d20['date_temp'] == (19+i)) & (d20['month'] == 9) 
                               & (d20['time'] > 44) & (d20['time'] < 51)]\
                               .sort_values(['time','tollgate_id','direction'])\
                               .reset_index().drop(['index'],axis=1)
    knn_training_list_20a.append(list(df_last2h_date_20a['volume']))
for i in xrange(17):
    df_last2h_date_20a = d20[(d20['date_temp'] == (8+i)) & (d20['month'] == 10) 
                                & (d20['time'] > 44) & (d20['time'] < 51)]\
                               .sort_values(['time','tollgate_id','direction'])\
                               .reset_index().drop(['index'],axis=1)
    knn_training_list_20a.append(list(df_last2h_date_20a['volume']))
    
for i in xrange(12):
    df_last2h_date_30a = d30[(d30['date_temp'] == (19+i)) & (d30['month'] == 9)
                                & (d30['time'] > 44) & (d30['time'] < 51)]\
                               .sort_values(['time','tollgate_id','direction'])\
                               .reset_index().drop(['index'],axis=1)
    knn_training_list_30a.append(list(df_last2h_date_30a['volume']))
for i in xrange(17):
    df_last2h_date_30a = d30[(d30['date_temp'] == (8+i)) & (d30['month'] == 10)
                               & (d30['time'] > 44) & (d30['time'] < 51)]\
                               .sort_values(['time','tollgate_id','direction'])\
                               .reset_index().drop(['index'],axis=1)
    knn_training_list_30a.append(list(df_last2h_date_30a['volume'])) 

for i in xrange(12):
    df_last2h_date_31a = d31[(d31['date_temp'] == (19+i)) & (d31['month'] == 9)
                                & (d31['time'] > 44) & (d31['time'] < 51)]\
                               .sort_values(['time','tollgate_id','direction'])\
                               .reset_index().drop(['index'],axis=1)
    knn_training_list_31a.append(list(df_last2h_date_31a['volume']))
for i in xrange(17):
    df_last2h_date_31a = d31[(d31['date_temp'] == (8+i)) & (d31['month'] == 10)
                                & (d31['time'] > 44) & (d31['time'] < 51)]\
                               .sort_values(['time','tollgate_id','direction'])\
                               .reset_index().drop(['index'],axis=1)
    knn_training_list_31a.append(list(df_last2h_date_31a['volume']))
training_label = [i for i in xrange(29)]
knn_training_list_20m
#training_label

[[30.0, 36.0, 37.0, 84.0, 80.0, 97.0],
 [33.0, 31.0, 54.0, 79.0, 86.0, 93.0],
 [6.0, 9.0, 14.0, 42.0, 37.0, 44.0],
 [30.0, 31.0, 38.0, 72.0, 79.0, 100.0],
 [31.0, 32.0, 54.0, 82.0, 91.0, 103.0],
 [30.0, 31.0, 45.0, 46.0, 64.0, 82.0],
 [22.0, 23.0, 29.0, 30.0, 45.0, 62.0],
 [25.0, 40.0, 73.0, 88.0, 114.0, 126.0],
 [28.0, 31.0, 43.0, 51.0, 89.0, 104.0],
 [5.0, 13.0, 26.0, 34.0, 48.0, 34.0],
 [15.0, 14.0, 32.0, 68.0, 72.0, 88.0],
 [35.0, 37.0, 52.0, 77.0, 86.0, 104.0],
 [25.0, 27.0, 37.0, 72.0, 77.0, 97.0],
 [29.0, 31.0, 45.0, 61.0, 99.0, 100.0],
 [23.0, 34.0, 49.0, 82.0, 114.0, 115.0],
 [25.0, 31.0, 52.0, 94.0, 109.0, 103.0],
 [32.0, 27.0, 45.0, 91.0, 92.0, 119.0],
 [23.0, 54.0, 66.0, 91.0, 107.0, 145.0],
 [20.0, 45.0, 47.0, 87.0, 96.0, 108.0],
 [21.0, 13.0, 42.044082641599999, 60.783870696999998, 50.0, 81.0],
 [12.0, 34.0, 34.0, 40.0, 69.0, 58.0],
 [31.0, 45.0, 52.0, 84.0, 125.0, 119.0],
 [24.0, 36.0, 46.0, 83.0, 87.0, 97.0],
 [26.0, 45.0, 47.0, 87.0, 95.0, 99.0],
 [21.0, 23.0, 42.0, 76.0, 89.0, 112.0],
 [16.0, 24.0, 39.0, 66.0, 77.0, 90.0],
 [22.0, 22.0, 43.0, 24.0, 49.0, 55.0],
 [8.0, 11.0, 25.0, 29.0, 35.0, 42.0],
 [27.0, 39.0, 52.0, 104.0, 111.0, 123.0]]

In [20]:
neigh10m = KNeighborsClassifier(n_neighbors=1)
neigh10m.fit(knn_training_list_10m, training_label)
neigh10m.predict(predict_list_10m)

array([ 4, 11, 23, 15, 12, 21,  9])

In [34]:
neigh11m = KNeighborsClassifier(n_neighbors=1)
neigh11m.fit(knn_training_list_11m, training_label) 
neigh11m.predict(predict_list_11m)

array([21, 29, 22,  3, 20,  6, 24])

In [21]:
neigh20m = KNeighborsClassifier(n_neighbors=1)
neigh20m.fit(knn_training_list_20m, training_label)
neigh20m.predict(predict_list_20m)

array([22,  3, 24, 13, 20, 27,  2])

In [36]:
neigh30m = KNeighborsClassifier(n_neighbors=1)
neigh30m.fit(knn_training_list_30m, training_label) 
neigh30m.predict(predict_list_30m)

array([ 9, 19, 31, 19,  6, 27, 28])

In [37]:
neigh31m = KNeighborsClassifier(n_neighbors=1)
neigh31m.fit(knn_training_list_31m, training_label) 
neigh31m.predict(predict_list_31m)

array([ 3, 32, 29, 20, 10, 10,  4])

In [39]:
neigh10a = KNeighborsClassifier(n_neighbors=1)
neigh10a.fit(knn_training_list_10a, training_label) 
neigh10a.predict(predict_list_10a)

array([ 2, 19, 31,  6,  3, 11,  9])

In [40]:
neigh11a = KNeighborsClassifier(n_neighbors=1)
neigh11a.fit(knn_training_list_11a, training_label) 
neigh11a.predict(predict_list_11a)

array([23, 28,  2, 27, 28, 34, 28])

In [22]:
neigh20a = KNeighborsClassifier(n_neighbors=1)
neigh20a.fit(knn_training_list_20a, training_label) 
neigh20a.predict(predict_list_20a)

array([25,  0, 13,  4, 10,  9,  9])

In [44]:
neigh30a = KNeighborsClassifier(n_neighbors=1)
neigh30a.fit(knn_training_list_30a, training_label) 
neigh30a.predict(predict_list_30a)

array([ 1, 27, 29,  4, 28, 25, 30])

In [45]:
neigh31a = KNeighborsClassifier(n_neighbors=1)
neigh31a.fit(knn_training_list_31a, training_label) 
neigh31a.predict(predict_list_31a)

array([ 0,  0, 20,  6, 22, 27, 29])