In [1]:
import math
from datetime import datetime,timedelta
import numpy as np
import pandas
import random
import preprocess_functions

In [2]:
df1 = pandas.read_csv("training_20min_avg_volume_etc_cartype.csv")
df2 = pandas.read_csv("training2_20min_avg_volume_etc_cartype.csv")
df = df1.append(df2, ignore_index=True)
df_time_temp = df['time_window'].str.split('[',expand=True)[1].str.split(',',expand=True)[0]
df['time_start'] = df_time_temp

In [3]:
df_add_time = preprocess_functions.add_time_dimension(df, df_time_temp)

In [4]:
df_truthm = df_add_time[(df_add_time['month']==10) & (df_add_time['date']>17) 
            & (df_add_time['time']>23) & (df_add_time['time']<30)].reset_index().drop(['index'],axis=1)
df_trutha = df_add_time[(df_add_time['month']==10) & (df_add_time['date']>17) 
            & (df_add_time['time']>50) & (df_add_time['time']<57)].reset_index().drop(['index'],axis=1)
dm_s = df_truthm.sort_values(['tollgate_id','direction','time']).reset_index().drop(['index'],axis=1)
da_s = df_trutha.sort_values(['tollgate_id','direction','time']).reset_index().drop(['index'],axis=1)
df_truth = dm_s.append(da_s,ignore_index=True)
df_truth

,tollgate_id,time_window,direction,volume,model0,model1,model2,model3,model4,model5,...,model7,type0,type1,has_etc1,time_start,month,weekday,time,hour,date
0,1,"[2016-10-18 08:00:00,2016-10-18 08:20:00)",0,50,0,48,1,1,0,0,...,0,0,0,12,2016-10-18 08:00:00,10,1,24,8,18
1,1,"[2016-10-19 08:00:00,2016-10-19 08:20:00)",0,48,0,44,2,2,0,0,...,0,0,0,19,2016-10-19 08:00:00,10,2,24,8,19
2,1,"[2016-10-20 08:00:00,2016-10-20 08:20:00)",0,50,0,43,5,1,1,0,...,0,0,0,17,2016-10-20 08:00:00,10,3,24,8,20
3,1,"[2016-10-21 08:00:00,2016-10-21 08:20:00)",0,37,0,33,2,1,1,0,...,0,0,0,17,2016-10-21 08:00:00,10,4,24,8,21
4,1,"[2016-10-22 08:00:00,2016-10-22 08:20:00)",0,35,0,29,5,1,0,0,...,0,0,0,10,2016-10-22 08:00:00,10,5,24,8,22
5,1,"[2016-10-23 08:00:00,2016-10-23 08:20:00)",0,30,0,23,7,0,0,0,...,0,0,0,8,2016-10-23 08:00:00,10,6,24,8,23
6,1,"[2016-10-24 08:00:00,2016-10-24 08:20:00)",0,49,0,46,3,0,0,0,...,0,0,0,18,2016-10-24 08:00:00,10,0,24,8,24
7,1,"[2016-10-18 08:20:00,2016-10-18 08:40:00)",0,41,0,38,2,1,0,0,...,0,0,0,13,2016-10-18 08:20:00,10,1,25,8,18
8,1,"[2016-10-19 08:20:00,2016-10-19 08:40:00)",0,50,0,44,4,1,1,0,...,0,0,0,22,2016-10-19 08:20:00,10,2,25,8,19
9,1,"[2016-10-20 08:20:00,2016-10-20 08:40:00)",0,49,0,46,1,2,0,0,...,0,0,0,17,2016-10-20 08:20:00,10,3,25,8,20
10,1,"[2016-10-21 08:20:00,2016-10-21 08:40:00)",0,46,0,43,2,1,0,0,...,0,0,0,14,2016-10-21 08:20:00,10,4,25,8,21
11,1,"[2016-10-22 08:20:00,2016-10-22 08:40:00)",0,52,0,46,2,4,0,0,...,0,0,0,19,2016-10-22 08:20:00,10,5,25,8,22
12,1,"[2016-10-23 08:20:00,2016-10-23 08:40:00)",0,28,0,19,2,3,4,0,...,0,0,0,10,2016-10-23 08:20:00,10,6,25,8,23
13,1,"[2016-10-24 08:20:00,2016-10-24 08:40:00)",0,47,0,44,1,2,0,0,...,0,0,0,12,2016-10-24 08:20:00,10,0,25,8,24
14,1,"[2016-10-18 08:40:00,2016-10-18 09:00:00)",0,49,0,47,1,1,0,0,...,0,0,0,15,2016-10-18 08:40:00,10,1,26,8,18
15,1,"[2016-10-19 08:40:00,2016-10-19 09:00:00)",0,50,0,42,7,1,0,0,...,0,0,0,11,2016-10-19 08:40:00,10,2,26,8,19
16,1,"[2016-10-20 08:40:00,2016-10-20 09:00:00)",0,62,0,59,2,1,0,0,...,0,0,0,22,2016-10-20 08:40:00,10,3,26,8,20
17,1,"[2016-10-21 08:40:00,2016-10-21 09:00:00)",0,46,0,38,6,2,0,0,...,0,0,0,10,2016-10-21 08:40:00,10,4,26,8,21
18,1,"[2016-10-22 08:40:00,2016-10-22 09:00:00)",0,39,0,35,3,1,0,0,...,0,0,0,7,2016-10-22 08:40:00,10,5,26,8,22
19,1,"[2016-10-23 08:40:00,2016-10-23 09:00:00)",0,37,0,36,1,0,0,0,...,0,0,0,13,2016-10-23 08:40:00,10,6,26,8,23
20,1,"[2016-10-24 08:40:00,2016-10-24 09:00:00)",0,50,0,47,2,1,0,0,...,0,0,0,12,2016-10-24 08:40:00,10,0,26,8,24
21,1,"[2016-10-18 09:00:00,2016-10-18 09:20:00)",0,61,0,53,7,0,1,0,...,0,0,0,12,2016-10-18 09:00:00,10,1,27,9,18
22,1,"[2016-10-19 09:00:00,2016-10-19 09:20:00)",0,42,0,41,0,0,1,0,...,0,0,0,14,2016-10-19 09:00:00,10,2,27,9,19
23,1,"[2016-10-20 09:00:00,2016-10-20 09:20:00)",0,38,0,33,4,1,0,0,...,0,0,0,14,2016-10-20 09:00:00,10,3,27,9,20
24,1,"[2016-10-21 09:00:00,2016-10-21 09:20:00)",0,38,0,33,5,0,0,0,...,0,0,0,11,2016-10-21 09:00:00,10,4,27,9,21
25,1,"[2016-10-22 09:00:00,2016-10-22 09:20:00)",0,57,0,54,3,0,0,0,...,0,0,0,9,2016-10-22 09:00:00,10,5,27,9,22
26,1,"[2016-10-23 09:00:00,2016-10-23 09:20:00)",0,45,0,43,2,0,0,0,...,0,0,0,13,2016-10-23 09:00:00,10,6,27,9,23
27,1,"[2016-10-24 09:00:00,2016-10-24 09:20:00)",0,52,0,50,2,0,0,0,...,0,0,0,15,2016-10-24 09:00:00,10,0,27,9,24
28,1,"[2016-10-18 09:20:00,2016-10-18 09:40:00)",0,39,0,35,3,0,1,0,...,0,0,0,10,2016-10-18 09:20:00,10,1,28,9,18
29,1,"[2016-10-19 09:20:00,2016-10-19 09:40:00)",0,38,0,35,3,0,0,0,...,0,0,0,12,2016-10-19 09:20:00,10,2,28,9,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,3,"[2016-10-23 17:20:00,2016-10-23 17:40:00)",1,81,0,77,1,1,0,2,...,0,75,6,19,2016-10-23 17:20:00,10,6,52,17,23
391,3,"[2016-10-24 17:20:00,2016-10-24 17:40:00)",1,97,0,92,3,0,0,2,...,0,92,5,19,2016-10-24 17:20:00,10,0,52,17,24
392,3,"[2016-10-18 17:40:00,2016-10-18 18:00:00)",1,86,0,78,4,3,1,0,...,0,77,9,34,2016-10-18 17:40:00,10,1,53,17,18
393,3,"[2016-10-19 17:40:00,2016-10-19 18:00:00)",1,87,0,83,2,0,0,2,...,0,81,6,30,2016-10-19 17:40:00,10,2,53,17,19
394,3,"[2016-10-20 17:40:00,2016-10-20 18:00:00)",1,80,0,77,1,1,0,1,...,0,73,7,31,2016-10-20 17:40:00,10,3,53,17,20
395,3,"[2016-10-21 17:40:00,2016-10-21 18:00:00)",1,70,0,61,3,2,2,2,...,0,64,6,20,2016-10-21 17:40:00,10,4,53,17,21
396,3,"[2016-10-22 17:40:00,2016-10-22 18:00:00)",1,65,0,62,3,0,0,0,...,0,57,8,10,2016-10-22 17:40:00,10,5,53,17,22
397,3,"[2016-10-23 17:40:00,2016-10-23 18:00:00)",1,76,0,69,3,1,3,0,...,0,71,5,13,2016-10-23 17:40:00,10,6,53,17,23
398,3,"[2016-10-24 17:40:00,2016-10-24 18:00:00)",1,80,0,75,2,0,1,2,...,0,71,9,30,2016-10-24 17:40:00,10,0,53,17,24
399,3,"[2016-10-18 18:00:00,2016-10-18 18:20:00)",1,73,0,64,6,1,1,1,...,0,65,8,17,2016-10-18 18:00:00,10,1,54,18,18
400,3,"[2016-10-19 18:00:00,2016-10-19 18:20:00)",1,71,0,64,2,1,2,2,...,0,66,5,26,2016-10-19 18:00:00,10,2,54,18,19
401,3,"[2016-10-20 18:00:00,2016-10-20 18:20:00)",1,54,0,51,1,2,0,0,...,0,49,5,15,2016-10-20 18:00:00,10,3,54,18,20
402,3,"[2016-10-21 18:00:00,2016-10-21 18:20:00)",1,62,0,54,2,2,1,3,...,0,54,8,19,2016-10-21 18:00:00,10,4,54,18,21
403,3,"[2016-10-22 18:00:00,2016-10-22 18:20:00)",1,56,0,51,0,2,0,3,...,0,50,6,16,2016-10-22 18:00:00,10,5,54,18,22
404,3,"[2016-10-23 18:00:00,2016-10-23 18:20:00)",1,78,0,77,0,0,0,1,...,0,76,2,15,2016-10-23 18:00:00,10,6,54,18,23
405,3,"[2016-10-24 18:00:00,2016-10-24 18:20:00)",1,91,0,83,4,0,3,1,...,0,83,8,34,2016-10-24 18:00:00,10,0,54,18,24
406,3,"[2016-10-18 18:20:00,2016-10-18 18:40:00)",1,65,0,58,3,3,0,1,...,0,58,7,20,2016-10-18 18:20:00,10,1,55,18,18
407,3,"[2016-10-19 18:20:00,2016-10-19 18:40:00)",1,77,0,72,2,1,1,1,...,0,67,10,25,2016-10-19 18:20:00,10,2,55,18,19
408,3,"[2016-10-20 18:20:00,2016-10-20 18:40:00)",1,78,0,75,1,1,0,1,...,0,75,3,24,2016-10-20 18:20:00,10,3,55,18,20
409,3,"[2016-10-21 18:20:00,2016-10-21 18:40:00)",1,73,0,69,0,3,0,1,...,0,64,9,18,2016-10-21 18:20:00,10,4,55,18,21
410,3,"[2016-10-22 18:20:00,2016-10-22 18:40:00)",1,55,0,53,0,0,0,2,...,0,51,4,8,2016-10-22 18:20:00,10,5,55,18,22
411,3,"[2016-10-23 18:20:00,2016-10-23 18:40:00)",1,88,0,82,2,0,2,2,...,0,80,8,23,2016-10-23 18:20:00,10,6,55,18,23
412,3,"[2016-10-24 18:20:00,2016-10-24 18:40:00)",1,94,0,88,4,1,0,1,...,0,83,11,31,2016-10-24 18:20:00,10,0,55,18,24
413,3,"[2016-10-18 18:40:00,2016-10-18 19:00:00)",1,68,0,61,2,1,1,3,...,0,61,7,13,2016-10-18 18:40:00,10,1,56,18,18
414,3,"[2016-10-19 18:40:00,2016-10-19 19:00:00)",1,80,0,71,4,0,2,3,...,0,67,13,24,2016-10-19 18:40:00,10,2,56,18,19
415,3,"[2016-10-20 18:40:00,2016-10-20 19:00:00)",1,66,0,58,3,2,1,2,...,0,60,6,17,2016-10-20 18:40:00,10,3,56,18,20
416,3,"[2016-10-21 18:40:00,2016-10-21 19:00:00)",1,58,0,50,2,2,2,2,...,0,52,6,14,2016-10-21 18:40:00,10,4,56,18,21
417,3,"[2016-10-22 18:40:00,2016-10-22 19:00:00)",1,77,0,70,4,0,0,3,...,0,68,9,22,2016-10-22 18:40:00,10,5,56,18,22
418,3,"[2016-10-23 18:40:00,2016-10-23 19:00:00)",1,79,0,76,1,1,1,0,...,0,73,6,21,2016-10-23 18:40:00,10,6,56,18,23
419,3,"[2016-10-24 18:40:00,2016-10-24 19:00:00)",1,74,0,68,4,1,1,0,...,0,66,8,21,2016-10-24 18:40:00,10,0,56,18,24

In [5]:
df_1_0 = preprocess_functions.extract_tg_dir(df, 1, 0)
df_1_1 = preprocess_functions.extract_tg_dir(df, 1, 1)
df_2_0 = preprocess_functions.extract_tg_dir(df, 2, 0)
df_3_0 = preprocess_functions.extract_tg_dir(df, 3, 0)
df_3_1 = preprocess_functions.extract_tg_dir(df, 3, 1)
df_1_0

,tollgate_id,time_window,direction,volume,model0,model1,model2,model3,model4,model5,...,model7,type0,type1,has_etc1,time_start,month,weekday,time,hour,date
0,1,"[2016-09-19 00:00:00,2016-09-19 00:20:00)",0,13,0,10,1,0,0,2,...,0,0,0,4,2016-09-19 00:00:00,9,0,0,0,19
1,1,"[2016-09-19 00:20:00,2016-09-19 00:40:00)",0,6,0,6,0,0,0,0,...,0,0,0,1,2016-09-19 00:20:00,9,0,1,0,19
2,1,"[2016-09-19 00:40:00,2016-09-19 01:00:00)",0,9,0,6,1,0,1,1,...,0,0,0,1,2016-09-19 00:40:00,9,0,2,0,19
3,1,"[2016-09-19 01:00:00,2016-09-19 01:20:00)",0,10,0,7,0,0,0,3,...,0,0,0,1,2016-09-19 01:00:00,9,0,3,1,19
4,1,"[2016-09-19 01:20:00,2016-09-19 01:40:00)",0,14,1,10,1,1,0,1,...,0,0,0,3,2016-09-19 01:20:00,9,0,4,1,19
5,1,"[2016-09-19 01:40:00,2016-09-19 02:00:00)",0,10,0,9,0,0,0,1,...,0,0,0,0,2016-09-19 01:40:00,9,0,5,1,19
6,1,"[2016-09-19 02:00:00,2016-09-19 02:20:00)",0,7,0,3,1,0,1,2,...,0,0,0,1,2016-09-19 02:00:00,9,0,6,2,19
7,1,"[2016-09-19 02:20:00,2016-09-19 02:40:00)",0,10,0,3,5,0,0,2,...,0,0,0,1,2016-09-19 02:20:00,9,0,7,2,19
8,1,"[2016-09-19 02:40:00,2016-09-19 03:00:00)",0,6,0,0,1,3,1,1,...,0,0,0,0,2016-09-19 02:40:00,9,0,8,2,19
9,1,"[2016-09-19 03:00:00,2016-09-19 03:20:00)",0,9,0,5,2,0,0,2,...,0,0,0,0,2016-09-19 03:00:00,9,0,9,3,19
10,1,"[2016-09-19 03:20:00,2016-09-19 03:40:00)",0,4,0,3,0,1,0,0,...,0,0,0,1,2016-09-19 03:20:00,9,0,10,3,19
11,1,"[2016-09-19 03:40:00,2016-09-19 04:00:00)",0,9,0,5,1,2,0,1,...,0,0,0,2,2016-09-19 03:40:00,9,0,11,3,19
12,1,"[2016-09-19 04:00:00,2016-09-19 04:20:00)",0,10,0,6,2,1,0,1,...,0,0,0,0,2016-09-19 04:00:00,9,0,12,4,19
13,1,"[2016-09-19 04:20:00,2016-09-19 04:40:00)",0,13,0,9,2,1,0,1,...,0,0,0,0,2016-09-19 04:20:00,9,0,13,4,19
14,1,"[2016-09-19 04:40:00,2016-09-19 05:00:00)",0,12,0,8,2,1,0,1,...,0,0,0,0,2016-09-19 04:40:00,9,0,14,4,19
15,1,"[2016-09-19 05:00:00,2016-09-19 05:20:00)",0,2,0,0,2,0,0,0,...,0,0,0,0,2016-09-19 05:00:00,9,0,15,5,19
16,1,"[2016-09-19 05:20:00,2016-09-19 05:40:00)",0,8,0,6,2,0,0,0,...,0,0,0,2,2016-09-19 05:20:00,9,0,16,5,19
17,1,"[2016-09-19 05:40:00,2016-09-19 06:00:00)",0,13,0,12,1,0,0,0,...,0,0,0,2,2016-09-19 05:40:00,9,0,17,5,19
18,1,"[2016-09-19 06:00:00,2016-09-19 06:20:00)",0,8,0,7,0,1,0,0,...,0,0,0,2,2016-09-19 06:00:00,9,0,18,6,19
19,1,"[2016-09-19 06:20:00,2016-09-19 06:40:00)",0,13,0,12,1,0,0,0,...,0,0,0,5,2016-09-19 06:20:00,9,0,19,6,19
20,1,"[2016-09-19 06:40:00,2016-09-19 07:00:00)",0,32,0,28,2,1,1,0,...,0,0,0,9,2016-09-19 06:40:00,9,0,20,6,19
21,1,"[2016-09-19 07:00:00,2016-09-19 07:20:00)",0,39,0,34,3,1,1,0,...,0,0,0,10,2016-09-19 07:00:00,9,0,21,7,19
22,1,"[2016-09-19 07:20:00,2016-09-19 07:40:00)",0,31,0,30,1,0,0,0,...,0,0,0,11,2016-09-19 07:20:00,9,0,22,7,19
23,1,"[2016-09-19 07:40:00,2016-09-19 08:00:00)",0,43,0,40,2,1,0,0,...,0,0,0,16,2016-09-19 07:40:00,9,0,23,7,19
24,1,"[2016-09-19 08:00:00,2016-09-19 08:20:00)",0,46,0,42,3,1,0,0,...,0,0,0,17,2016-09-19 08:00:00,9,0,24,8,19
25,1,"[2016-09-19 08:20:00,2016-09-19 08:40:00)",0,56,0,49,4,2,1,0,...,0,0,0,17,2016-09-19 08:20:00,9,0,25,8,19
26,1,"[2016-09-19 08:40:00,2016-09-19 09:00:00)",0,41,9,30,1,1,0,0,...,0,0,0,9,2016-09-19 08:40:00,9,0,26,8,19
27,1,"[2016-09-19 09:00:00,2016-09-19 09:20:00)",0,50,0,44,6,0,0,0,...,0,0,0,18,2016-09-19 09:00:00,9,0,27,9,19
28,1,"[2016-09-19 09:20:00,2016-09-19 09:40:00)",0,49,0,41,7,0,1,0,...,0,0,0,10,2016-09-19 09:20:00,9,0,28,9,19
29,1,"[2016-09-19 09:40:00,2016-09-19 10:00:00)",0,44,0,42,2,0,0,0,...,0,0,0,3,2016-09-19 09:40:00,9,0,29,9,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2562,1,"[2016-10-24 14:00:00,2016-10-24 14:20:00)",0,47,0,40,5,2,0,0,...,0,0,0,15,2016-10-24 14:00:00,10,0,42,14,24
2563,1,"[2016-10-24 14:20:00,2016-10-24 14:40:00)",0,49,0,40,9,0,0,0,...,0,0,0,8,2016-10-24 14:20:00,10,0,43,14,24
2564,1,"[2016-10-24 14:40:00,2016-10-24 15:00:00)",0,44,0,40,4,0,0,0,...,0,0,0,9,2016-10-24 14:40:00,10,0,44,14,24
2565,1,"[2016-10-24 15:00:00,2016-10-24 15:20:00)",0,50,0,46,3,1,0,0,...,0,0,0,3,2016-10-24 15:00:00,10,0,45,15,24
2566,1,"[2016-10-24 15:20:00,2016-10-24 15:40:00)",0,47,0,43,4,0,0,0,...,0,0,0,13,2016-10-24 15:20:00,10,0,46,15,24
2567,1,"[2016-10-24 15:40:00,2016-10-24 16:00:00)",0,26,0,25,1,0,0,0,...,0,0,0,7,2016-10-24 15:40:00,10,0,47,15,24
2568,1,"[2016-10-24 16:00:00,2016-10-24 16:20:00)",0,49,0,47,2,0,0,0,...,0,0,0,7,2016-10-24 16:00:00,10,0,48,16,24
2569,1,"[2016-10-24 16:20:00,2016-10-24 16:40:00)",0,50,0,44,4,1,1,0,...,0,0,0,15,2016-10-24 16:20:00,10,0,49,16,24
2570,1,"[2016-10-24 16:40:00,2016-10-24 17:00:00)",0,44,0,40,3,0,1,0,...,0,0,0,11,2016-10-24 16:40:00,10,0,50,16,24
2571,1,"[2016-10-24 17:00:00,2016-10-24 17:20:00)",0,32,0,30,2,0,0,0,...,0,0,0,6,2016-10-24 17:00:00,10,0,51,17,24
2572,1,"[2016-10-24 17:20:00,2016-10-24 17:40:00)",0,39,0,36,0,0,3,0,...,0,0,0,13,2016-10-24 17:20:00,10,0,52,17,24
2573,1,"[2016-10-24 17:40:00,2016-10-24 18:00:00)",0,29,0,28,1,0,0,0,...,0,0,0,10,2016-10-24 17:40:00,10,0,53,17,24
2574,1,"[2016-10-24 18:00:00,2016-10-24 18:20:00)",0,15,0,12,3,0,0,0,...,0,0,0,3,2016-10-24 18:00:00,10,0,54,18,24
2575,1,"[2016-10-24 18:20:00,2016-10-24 18:40:00)",0,18,0,17,1,0,0,0,...,0,0,0,3,2016-10-24 18:20:00,10,0,55,18,24
2576,1,"[2016-10-24 18:40:00,2016-10-24 19:00:00)",0,13,0,13,0,0,0,0,...,0,0,0,5,2016-10-24 18:40:00,10,0,56,18,24
2577,1,"[2016-10-24 19:00:00,2016-10-24 19:20:00)",0,27,0,27,0,0,0,0,...,0,0,0,4,2016-10-24 19:00:00,10,0,57,19,24
2578,1,"[2016-10-24 19:20:00,2016-10-24 19:40:00)",0,16,0,15,1,0,0,0,...,0,0,0,4,2016-10-24 19:20:00,10,0,58,19,24
2579,1,"[2016-10-24 19:40:00,2016-10-24 20:00:00)",0,10,0,10,0,0,0,0,...,0,0,0,2,2016-10-24 19:40:00,10,0,59,19,24
2580,1,"[2016-10-24 20:00:00,2016-10-24 20:20:00)",0,18,0,17,1,0,0,0,...,0,0,0,7,2016-10-24 20:00:00,10,0,60,20,24
2581,1,"[2016-10-24 20:20:00,2016-10-24 20:40:00)",0,19,0,17,2,0,0,0,...,0,0,0,6,2016-10-24 20:20:00,10,0,61,20,24
2582,1,"[2016-10-24 20:40:00,2016-10-24 21:00:00)",0,17,0,13,3,0,1,0,...,0,0,0,5,2016-10-24 20:40:00,10,0,62,20,24
2583,1,"[2016-10-24 21:00:00,2016-10-24 21:20:00)",0,19,0,15,4,0,0,0,...,0,0,0,5,2016-10-24 21:00:00,10,0,63,21,24
2584,1,"[2016-10-24 21:20:00,2016-10-24 21:40:00)",0,14,0,12,2,0,0,0,...,0,0,0,3,2016-10-24 21:20:00,10,0,64,21,24
2585,1,"[2016-10-24 21:40:00,2016-10-24 22:00:00)",0,14,0,13,1,0,0,0,...,0,0,0,1,2016-10-24 21:40:00,10,0,65,21,24
2586,1,"[2016-10-24 22:00:00,2016-10-24 22:20:00)",0,10,0,10,0,0,0,0,...,0,0,0,2,2016-10-24 22:00:00,10,0,66,22,24
2587,1,"[2016-10-24 22:20:00,2016-10-24 22:40:00)",0,11,0,9,2,0,0,0,...,0,0,0,2,2016-10-24 22:20:00,10,0,67,22,24
2588,1,"[2016-10-24 22:40:00,2016-10-24 23:00:00)",0,7,0,5,2,0,0,0,...,0,0,0,3,2016-10-24 22:40:00,10,0,68,22,24
2589,1,"[2016-10-24 23:00:00,2016-10-24 23:20:00)",0,11,0,8,3,0,0,0,...,0,0,0,1,2016-10-24 23:00:00,10,0,69,23,24
2590,1,"[2016-10-24 23:20:00,2016-10-24 23:40:00)",0,7,0,7,0,0,0,0,...,0,0,0,1,2016-10-24 23:20:00,10,0,70,23,24
2591,1,"[2016-10-24 23:40:00,2016-10-25 00:00:00)",0,2,0,2,0,0,0,0,...,0,0,0,0,2016-10-24 23:40:00,10,0,71,23,24

In [8]:
df_1_0_vacancy = df_1_0[df_1_0['volume']==0]
df_1_1_vacancy = df_1_1[df_1_1['volume']==0]
df_2_0_vacancy = df_2_0[df_2_0['volume']==0]
df_3_0_vacancy = df_3_0[df_3_0['volume']==0]
df_3_1_vacancy = df_3_1[df_3_1['volume']==0]
frame_fill = [df_1_0_vacancy,df_1_1_vacancy,df_2_0_vacancy,df_3_0_vacancy,df_3_1_vacancy]
df_vacancy = pandas.concat(frame_fill,ignore_index=True)
df_vacancy_new = df_vacancy['time_start'].apply(str)
df_vacancy.to_csv('phase2_wait_fill_vacancy.csv',index=False)

In [11]:
df_weather1 = pandas.read_csv("v3_weather (table 7)_training.csv")
df_weather2 = pandas.read_csv("v2_weather (table 7)_test.csv")
df_weather_temp = df_weather1.append(df_weather2, ignore_index=True)

In [23]:
df_waitfill = pandas.read_csv('phase2_wait_fill_vacancy.csv')
df_waitfill_temp = df_waitfill['time_start']
df_waitfill_insert_weather = preprocess_functions.insert_weather(df_waitfill, df_waitfill_temp, df_weather_temp)
df_waitfill_add_time = preprocess_functions.add_time_dimension(df_waitfill_insert_weather, df_waitfill_temp)
df_final_test = preprocess_functions.holiday_judge(df_waitfill_add_time, df_waitfill_temp)
df_final_test

,tollgate_id,time_window,direction,volume,model0,model1,model2,model3,model4,model5,...,month,weekday,time,hour,date,precipitation,wind_speed,temperature,humidity,holiday_ornot
0,1,"[2016-10-02 00:00:00,2016-10-02 00:20:00)",0,0,1,1,1,1,1,1,...,10,5,71,23,1,0.0,2.0,23.7,95.0,1
1,1,"[2016-10-02 23:20:00,2016-10-02 23:40:00)",0,0,1,1,1,1,1,1,...,10,6,69,23,2,0.0,2.0,22.6,90.0,1
2,1,"[2016-10-09 00:00:00,2016-10-09 00:20:00)",0,0,1,1,1,1,1,1,...,10,3,71,23,8,0.0,2.0,16.5,64.0,0
3,1,"[2016-10-09 23:20:00,2016-10-09 23:40:00)",0,0,1,1,1,1,1,1,...,10,4,69,23,9,0.0,2.0,14.1,80.0,0
4,1,"[2016-10-01 01:20:00,2016-10-01 01:40:00)",1,0,1,1,1,1,1,1,...,10,5,3,1,1,0.0,0.0,22.3,93.0,0
5,1,"[2016-10-01 02:00:00,2016-10-01 02:20:00)",1,0,1,1,1,1,1,1,...,10,5,5,1,1,0.0,0.0,22.3,93.0,0
6,1,"[2016-10-02 22:20:00,2016-10-02 22:40:00)",1,0,1,1,1,1,1,1,...,10,6,66,22,2,0.0,2.0,22.6,90.0,0
7,1,"[2016-10-07 01:20:00,2016-10-07 01:40:00)",1,0,1,1,1,1,1,1,...,10,4,3,1,7,0.0,2.0,20.3,83.0,0
8,2,"[2016-09-19 01:00:00,2016-09-19 01:20:00)",0,0,1,1,1,1,1,1,...,9,0,1,0,19,0.0,2.0,22.2,76.0,0
9,2,"[2016-09-19 01:00:00,2016-09-19 01:20:00)",0,0,1,1,1,1,1,1,...,9,0,2,0,19,0.0,2.0,22.2,76.0,0
10,2,"[2016-09-19 01:40:00,2016-09-19 02:00:00)",0,0,1,1,1,1,1,1,...,9,0,4,1,19,0.0,2.0,22.2,76.0,0
11,2,"[2016-09-19 05:00:00,2016-09-19 05:20:00)",0,0,1,1,1,1,1,1,...,9,0,6,2,19,0.0,2.0,22.2,76.0,0
12,2,"[2016-09-19 05:00:00,2016-09-19 05:20:00)",0,0,1,1,1,1,1,1,...,9,0,7,2,19,0.0,2.0,22.2,76.0,0
13,2,"[2016-09-19 05:00:00,2016-09-19 05:20:00)",0,0,1,1,1,1,1,1,...,9,0,8,2,19,0.0,2.0,22.2,76.0,0
14,2,"[2016-09-19 05:00:00,2016-09-19 05:20:00)",0,0,1,1,1,1,1,1,...,9,0,9,3,19,0.0,2.0,24.4,67.0,0
15,2,"[2016-09-19 05:00:00,2016-09-19 05:20:00)",0,0,1,1,1,1,1,1,...,9,0,10,3,19,0.0,2.0,24.4,67.0,0
16,2,"[2016-09-19 05:00:00,2016-09-19 05:20:00)",0,0,1,1,1,1,1,1,...,9,0,11,3,19,0.0,2.0,24.4,67.0,0
17,2,"[2016-09-19 05:00:00,2016-09-19 05:20:00)",0,0,1,1,1,1,1,1,...,9,0,12,4,19,0.0,2.0,24.4,67.0,0
18,2,"[2016-09-19 05:00:00,2016-09-19 05:20:00)",0,0,1,1,1,1,1,1,...,9,0,13,4,19,0.0,2.0,24.4,67.0,0
19,2,"[2016-09-19 05:00:00,2016-09-19 05:20:00)",0,0,1,1,1,1,1,1,...,9,0,14,4,19,0.0,2.0,24.4,67.0,0
20,2,"[2016-09-20 00:20:00,2016-09-20 00:40:00)",0,0,1,1,1,1,1,1,...,9,1,0,0,20,0.0,2.0,21.1,68.0,0
21,2,"[2016-09-20 01:20:00,2016-09-20 01:40:00)",0,0,1,1,1,1,1,1,...,9,1,3,1,20,0.0,2.0,21.1,68.0,0
22,2,"[2016-09-20 05:00:00,2016-09-20 05:20:00)",0,0,1,1,1,1,1,1,...,9,1,5,1,20,0.0,2.0,21.1,68.0,0
23,2,"[2016-09-20 05:00:00,2016-09-20 05:20:00)",0,0,1,1,1,1,1,1,...,9,1,6,2,20,0.0,2.0,21.1,68.0,0
24,2,"[2016-09-20 05:00:00,2016-09-20 05:20:00)",0,0,1,1,1,1,1,1,...,9,1,7,2,20,0.0,2.0,21.1,68.0,0
25,2,"[2016-09-20 05:00:00,2016-09-20 05:20:00)",0,0,1,1,1,1,1,1,...,9,1,8,2,20,0.0,2.0,21.1,68.0,0
26,2,"[2016-09-20 05:00:00,2016-09-20 05:20:00)",0,0,1,1,1,1,1,1,...,9,1,9,3,20,0.0,2.0,23.9,58.0,0
27,2,"[2016-09-20 05:00:00,2016-09-20 05:20:00)",0,0,1,1,1,1,1,1,...,9,1,10,3,20,0.0,2.0,23.9,58.0,0
28,2,"[2016-09-20 05:00:00,2016-09-20 05:20:00)",0,0,1,1,1,1,1,1,...,9,1,11,3,20,0.0,2.0,23.9,58.0,0
29,2,"[2016-09-20 05:00:00,2016-09-20 05:20:00)",0,0,1,1,1,1,1,1,...,9,1,12,4,20,0.0,2.0,23.9,58.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
422,2,"[2016-10-22 04:40:00,2016-10-22 05:00:00)",0,0,1,1,1,1,1,1,...,10,5,13,4,22,1.0,2.0,22.4,96.0,0
423,2,"[2016-10-23 00:40:00,2016-10-23 01:00:00)",0,0,1,1,1,1,1,1,...,10,6,1,0,23,0.0,2.0,19.6,93.0,0
424,2,"[2016-10-23 04:00:00,2016-10-23 04:20:00)",0,0,1,1,1,1,1,1,...,10,6,3,1,23,0.0,2.0,19.6,93.0,0
425,2,"[2016-10-23 04:00:00,2016-10-23 04:20:00)",0,0,1,1,1,1,1,1,...,10,6,4,1,23,0.0,2.0,19.6,93.0,0
426,2,"[2016-10-23 04:00:00,2016-10-23 04:20:00)",0,0,1,1,1,1,1,1,...,10,6,5,1,23,0.0,2.0,19.6,93.0,0
427,2,"[2016-10-23 04:00:00,2016-10-23 04:20:00)",0,0,1,1,1,1,1,1,...,10,6,6,2,23,0.0,2.0,19.6,93.0,0
428,2,"[2016-10-23 04:00:00,2016-10-23 04:20:00)",0,0,1,1,1,1,1,1,...,10,6,7,2,23,0.0,2.0,19.6,93.0,0
429,2,"[2016-10-23 04:00:00,2016-10-23 04:20:00)",0,0,1,1,1,1,1,1,...,10,6,8,2,23,0.0,2.0,19.6,93.0,0
430,2,"[2016-10-23 04:00:00,2016-10-23 04:20:00)",0,0,1,1,1,1,1,1,...,10,6,9,3,23,0.0,2.0,21.0,83.0,0
431,2,"[2016-10-23 04:00:00,2016-10-23 04:20:00)",0,0,1,1,1,1,1,1,...,10,6,10,3,23,0.0,2.0,21.0,83.0,0
432,2,"[2016-10-23 04:00:00,2016-10-23 04:20:00)",0,0,1,1,1,1,1,1,...,10,6,11,3,23,0.0,2.0,21.0,83.0,0
433,2,"[2016-10-23 05:00:00,2016-10-23 05:20:00)",0,0,1,1,1,1,1,1,...,10,6,13,4,23,0.0,2.0,21.0,83.0,0
434,2,"[2016-10-23 05:00:00,2016-10-23 05:20:00)",0,0,1,1,1,1,1,1,...,10,6,14,4,23,0.0,2.0,21.0,83.0,0
435,2,"[2016-10-24 01:20:00,2016-10-24 01:40:00)",0,0,1,1,1,1,1,1,...,10,0,2,0,24,0.0,2.0,20.4,87.0,0
436,2,"[2016-10-24 01:20:00,2016-10-24 01:40:00)",0,0,1,1,1,1,1,1,...,10,0,3,1,24,0.0,2.0,20.4,87.0,0
437,2,"[2016-10-24 04:40:00,2016-10-24 05:00:00)",0,0,1,1,1,1,1,1,...,10,0,5,1,24,0.0,2.0,20.4,87.0,0
438,2,"[2016-10-24 04:40:00,2016-10-24 05:00:00)",0,0,1,1,1,1,1,1,...,10,0,6,2,24,0.0,2.0,20.4,87.0,0
439,2,"[2016-10-24 04:40:00,2016-10-24 05:00:00)",0,0,1,1,1,1,1,1,...,10,0,7,2,24,0.0,2.0,20.4,87.0,0
440,2,"[2016-10-24 04:40:00,2016-10-24 05:00:00)",0,0,1,1,1,1,1,1,...,10,0,8,2,24,0.0,2.0,20.4,87.0,0
441,2,"[2016-10-24 04:40:00,2016-10-24 05:00:00)",0,0,1,1,1,1,1,1,...,10,0,9,3,24,0.0,1.0,23.4,75.0,0
442,2,"[2016-10-24 04:40:00,2016-10-24 05:00:00)",0,0,1,1,1,1,1,1,...,10,0,10,3,24,0.0,1.0,23.4,75.0,0
443,2,"[2016-10-24 04:40:00,2016-10-24 05:00:00)",0,0,1,1,1,1,1,1,...,10,0,11,3,24,0.0,1.0,23.4,75.0,0
444,2,"[2016-10-24 04:40:00,2016-10-24 05:00:00)",0,0,1,1,1,1,1,1,...,10,0,12,4,24,0.0,1.0,23.4,75.0,0
445,2,"[2016-10-24 04:40:00,2016-10-24 05:00:00)",0,0,1,1,1,1,1,1,...,10,0,13,4,24,0.0,1.0,23.4,75.0,0
446,3,"[2016-10-02 00:00:00,2016-10-02 00:20:00)",0,0,1,1,1,1,1,1,...,10,5,71,23,1,0.0,2.0,23.7,95.0,1
447,3,"[2016-10-09 00:00:00,2016-10-09 00:20:00)",0,0,1,1,1,1,1,1,...,10,3,71,23,8,0.0,2.0,16.5,64.0,0
448,3,"[2016-09-19 03:00:00,2016-09-19 03:20:00)",1,0,1,1,1,1,1,1,...,9,0,8,2,19,0.0,2.0,22.2,76.0,0
449,3,"[2016-10-04 00:00:00,2016-10-04 00:20:00)",1,0,1,1,1,1,1,1,...,10,0,71,23,3,0.0,2.0,20.7,88.0,0
450,3,"[2016-10-04 01:40:00,2016-10-04 02:00:00)",1,0,1,1,1,1,1,1,...,10,1,4,1,4,0.0,2.0,21.6,84.0,0
451,3,"[2016-10-24 03:40:00,2016-10-24 04:00:00)",1,0,1,1,1,1,1,1,...,10,0,10,3,24,0.0,1.0,23.4,75.0,0

In [24]:
df_addition = pandas.DataFrame({'time':[i for i in xrange(72)]})
df_final_test = df_final_test.append(df_addition,ignore_index=True)
df_final_test = df_final_test.fillna('2016-3-19 00:00:00')
df_final_test['time_hour'] = df_final_test['time_start'].str.split('-',expand=True)[2]\
                             .str.split(' ',expand=True)[1].str.split(':',expand=True)[0].apply(int)
df_final_test['date'] = df_final_test['time_start'].str.split('-',expand=True)[2]\
                             .str.split(' ',expand=True)[0].apply(int)
df_final_test['minute'] = df_final_test['time_start'].str.split('-',expand=True)[2]\
                             .str.split(' ',expand=True)[1].str.split(':',expand=True)[1].apply(int)

In [25]:
preprocess_functions.insert_onehot(df_final_test, 'tollgate_id')
preprocess_functions.insert_onehot(df_final_test, 'month')
preprocess_functions.insert_onehot(df_final_test, 'weekday')
preprocess_functions.insert_onehot(df_final_test, 'time')
preprocess_functions.insert_onehot(df_final_test, 'precipitation')
df_final_test

,precipitation3,precipitation2,precipitation1,precipitation0,time71,time70,time69,time68,time67,time66,...,time_start,time_window,tollgate_id,type0,type1,volume,weekday,wind_speed,time_hour,minute
0,0,0,0,1,1,0,0,0,0,0,...,2016-10-01 23:40:00,"[2016-10-02 00:00:00,2016-10-02 00:20:00)",1,1,1,0,5,2,23,40
1,0,0,0,1,0,0,1,0,0,0,...,2016-10-02 23:00:00,"[2016-10-02 23:20:00,2016-10-02 23:40:00)",1,1,1,0,6,2,23,0
2,0,0,0,1,1,0,0,0,0,0,...,2016-10-08 23:40:00,"[2016-10-09 00:00:00,2016-10-09 00:20:00)",1,1,1,0,3,2,23,40
3,0,0,0,1,0,0,1,0,0,0,...,2016-10-09 23:00:00,"[2016-10-09 23:20:00,2016-10-09 23:40:00)",1,1,1,0,4,2,23,0
4,0,0,0,1,0,0,0,0,0,0,...,2016-10-01 01:00:00,"[2016-10-01 01:20:00,2016-10-01 01:40:00)",1,1,1,0,5,0,1,0
5,0,0,0,1,0,0,0,0,0,0,...,2016-10-01 01:40:00,"[2016-10-01 02:00:00,2016-10-01 02:20:00)",1,1,1,0,5,0,1,40
6,0,0,0,1,0,0,0,0,0,1,...,2016-10-02 22:00:00,"[2016-10-02 22:20:00,2016-10-02 22:40:00)",1,1,1,0,6,2,22,0
7,0,0,0,1,0,0,0,0,0,0,...,2016-10-07 01:00:00,"[2016-10-07 01:20:00,2016-10-07 01:40:00)",1,1,1,0,4,2,1,0
8,0,0,0,1,0,0,0,0,0,0,...,2016-09-19 00:20:00,"[2016-09-19 01:00:00,2016-09-19 01:20:00)",2,1,1,0,0,2,0,20
9,0,0,0,1,0,0,0,0,0,0,...,2016-09-19 00:40:00,"[2016-09-19 01:00:00,2016-09-19 01:20:00)",2,1,1,0,0,2,0,40
10,0,0,0,1,0,0,0,0,0,0,...,2016-09-19 01:20:00,"[2016-09-19 01:40:00,2016-09-19 02:00:00)",2,1,1,0,0,2,1,20
11,0,0,0,1,0,0,0,0,0,0,...,2016-09-19 02:00:00,"[2016-09-19 05:00:00,2016-09-19 05:20:00)",2,1,1,0,0,2,2,0
12,0,0,0,1,0,0,0,0,0,0,...,2016-09-19 02:20:00,"[2016-09-19 05:00:00,2016-09-19 05:20:00)",2,1,1,0,0,2,2,20
13,0,0,0,1,0,0,0,0,0,0,...,2016-09-19 02:40:00,"[2016-09-19 05:00:00,2016-09-19 05:20:00)",2,1,1,0,0,2,2,40
14,0,0,0,1,0,0,0,0,0,0,...,2016-09-19 03:00:00,"[2016-09-19 05:00:00,2016-09-19 05:20:00)",2,1,1,0,0,2,3,0
15,0,0,0,1,0,0,0,0,0,0,...,2016-09-19 03:20:00,"[2016-09-19 05:00:00,2016-09-19 05:20:00)",2,1,1,0,0,2,3,20
16,0,0,0,1,0,0,0,0,0,0,...,2016-09-19 03:40:00,"[2016-09-19 05:00:00,2016-09-19 05:20:00)",2,1,1,0,0,2,3,40
17,0,0,0,1,0,0,0,0,0,0,...,2016-09-19 04:00:00,"[2016-09-19 05:00:00,2016-09-19 05:20:00)",2,1,1,0,0,2,4,0
18,0,0,0,1,0,0,0,0,0,0,...,2016-09-19 04:20:00,"[2016-09-19 05:00:00,2016-09-19 05:20:00)",2,1,1,0,0,2,4,20
19,0,0,0,1,0,0,0,0,0,0,...,2016-09-19 04:40:00,"[2016-09-19 05:00:00,2016-09-19 05:20:00)",2,1,1,0,0,2,4,40
20,0,0,0,1,0,0,0,0,0,0,...,2016-09-20 00:00:00,"[2016-09-20 00:20:00,2016-09-20 00:40:00)",2,1,1,0,1,2,0,0
21,0,0,0,1,0,0,0,0,0,0,...,2016-09-20 01:00:00,"[2016-09-20 01:20:00,2016-09-20 01:40:00)",2,1,1,0,1,2,1,0
22,0,0,0,1,0,0,0,0,0,0,...,2016-09-20 01:40:00,"[2016-09-20 05:00:00,2016-09-20 05:20:00)",2,1,1,0,1,2,1,40
23,0,0,0,1,0,0,0,0,0,0,...,2016-09-20 02:00:00,"[2016-09-20 05:00:00,2016-09-20 05:20:00)",2,1,1,0,1,2,2,0
24,0,0,0,1,0,0,0,0,0,0,...,2016-09-20 02:20:00,"[2016-09-20 05:00:00,2016-09-20 05:20:00)",2,1,1,0,1,2,2,20
25,0,0,0,1,0,0,0,0,0,0,...,2016-09-20 02:40:00,"[2016-09-20 05:00:00,2016-09-20 05:20:00)",2,1,1,0,1,2,2,40
26,0,0,0,1,0,0,0,0,0,0,...,2016-09-20 03:00:00,"[2016-09-20 05:00:00,2016-09-20 05:20:00)",2,1,1,0,1,2,3,0
27,0,0,0,1,0,0,0,0,0,0,...,2016-09-20 03:20:00,"[2016-09-20 05:00:00,2016-09-20 05:20:00)",2,1,1,0,1,2,3,20
28,0,0,0,1,0,0,0,0,0,0,...,2016-09-20 03:40:00,"[2016-09-20 05:00:00,2016-09-20 05:20:00)",2,1,1,0,1,2,3,40
29,0,0,0,1,0,0,0,0,0,0,...,2016-09-20 04:00:00,"[2016-09-20 05:00:00,2016-09-20 05:20:00)",2,1,1,0,1,2,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
494,1,0,0,0,0,0,0,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
495,1,0,0,0,0,0,0,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
496,1,0,0,0,0,0,0,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
497,1,0,0,0,0,0,0,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
498,1,0,0,0,0,0,0,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
499,1,0,0,0,0,0,0,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
500,1,0,0,0,0,0,0,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
501,1,0,0,0,0,0,0,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
502,1,0,0,0,0,0,0,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
503,1,0,0,0,0,0,0,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
504,1,0,0,0,0,0,0,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
505,1,0,0,0,0,0,0,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
506,1,0,0,0,0,0,0,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
507,1,0,0,0,0,0,0,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
508,1,0,0,0,0,0,0,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
509,1,0,0,0,0,0,0,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
510,1,0,0,0,0,0,0,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
511,1,0,0,0,0,0,0,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
512,1,0,0,0,0,0,0,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
513,1,0,0,0,0,0,0,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
514,1,0,0,0,0,0,0,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
515,1,0,0,0,0,0,0,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
516,1,0,0,0,0,0,0,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
517,1,0,0,0,0,0,0,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
518,1,0,0,0,0,0,0,0,0,1,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
519,1,0,0,0,0,0,0,0,1,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
520,1,0,0,0,0,0,0,1,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
521,1,0,0,0,0,0,1,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
522,1,0,0,0,0,1,0,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0
523,1,0,0,0,1,0,0,0,0,0,...,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,2016-3-19 00:00:00,0,0

In [26]:
df_final_test.drop([(i+452) for i in xrange(72)],inplace=True)

In [28]:
df_final_test.to_csv('phase2_wait_train_fill.csv')